In [71]:
import pandas as pd
import numpy as np

# Importing the Data Frame from IBGE
file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 1.1 (Pop_Geo).xls'
df_Demographic_Distribution = pd.read_excel(file_path, sheet_name = '2021')
df_cleaned = df_Demographic_Distribution.copy()
df_cleaned

,"Tabela 1.1 - Distribuição da população, por cor ou raça, segundo Grandes Regiões e Unidades da Federação - Brasil - 2021",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,Grandes Regiões e Unidades da Federação,População,NaN,NaN,NaN,NaN
3,NaN,Total\n(1 000 pessoas),Distribuição percentual por cor ou raça (%),NaN,NaN,NaN
4,NaN,NaN,Branca,Preta,Parda,Preta ou parda
5,Brasil,212650.323424,43.013008,9.075108,46.979981,56.055089
6,Norte,18577.619045,17.652349,7.473744,73.421972,80.895716
7,Rondônia,1804.543005,30.216115,8.235032,60.920943,69.155975
8,Acre,889.829002,15.587439,6.046421,77.040416,83.086837
9,Amazonas,4103.520007,14.343252,3.019257,80.135778,83.155035
10,Roraima,582.002001,20.588836,6.581009,67.817195,74.398204
11,Pará,8734.77202,16.618436,8.875837,73.505418,82.381255
12,Amapá,869.050004,15.040915,7.214187,77.265284,84.479471
13,Tocantins,1593.903005,19.117883,11.660672,67.763967,79.424639
14,Nordeste,57522.022114,24.669586,11.42573,63.146718,74.572448
15,Maranhão,7118.214015,16.997795,10.938734,71.239743,82.178477
16,Piauí,3288.504006,19.944566,8.397647,71.48792,79.885567
17,Ceará,9237.820018,25.544402,6.019584,67.666491,73.686075
18,Rio Grande do Norte,3560.903009,39.1464,8.275301,52.312423,60.587724
19,Paraíba,4038.225008,32.320926,7.157185,59.929329,67.086514
20,Pernambuco,9616.357021,31.198085,7.429437,60.44848,67.877917
21,Alagoas,3358.030008,28.269205,6.21424,64.567702,70.781942
22,Sergipe,2338.333004,21.99152,10.315805,67.345875,77.661681
23,Bahia,14965.636026,18.723439,21.471854,58.879481,80.351335
24,Sudeste,89611.153162,50.705709,9.574281,38.65795,48.232231
25,Minas Gerais,21401.130041,41.760881,10.344057,47.671703,58.01576
26,Espírito Santo,4104.647009,35.17451,12.25137,51.965548,64.216919
27,Rio de Janeiro,17462.80103,44.828756,14.212976,40.225419,54.438395
28,São Paulo,46642.575082,58.376974,7.248784,32.764196,40.01298
29,Sul,30358.784061,75.145761,4.350884,19.900269,24.251153
30,Paraná,11584.089024,65.526738,3.655889,29.797261,33.45315
31,Santa Catarina,7326.578015,81.503231,3.354458,14.694479,18.048937
32,Rio Grande do Sul,11448.117021,80.810372,5.691829,13.217334,18.909163
33,Centro-Oeste,16580.745043,34.655627,8.666632,55.826463,64.493095
34,Mato Grosso do Sul,2768.103008,42.995133,6.096721,49.599682,55.696404
35,Mato Grosso,3512.138009,29.440797,9.650145,59.795299,69.445444
36,Goiás,7208.837019,32.509622,8.253427,58.744707,66.998135
37,Distrito Federal,3091.667006,38.116797,10.813779,50.088498,60.902277
38,NaN,NaN,NaN,NaN,NaN,NaN
39,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN,NaN

In [72]:
# By dropping all the NaN rows values
df_cleaned = df_cleaned.dropna(how = 'all')
# Setting the 4 row to be the column name, it will be easier to melt
df_cleaned.columns = df_cleaned.iloc[2]
df_cleaned

4,NaN,NaN,Branca,Preta,Parda,Preta ou parda
2,Grandes Regiões e Unidades da Federação,População,NaN,NaN,NaN,NaN
3,NaN,Total\n(1 000 pessoas),Distribuição percentual por cor ou raça (%),NaN,NaN,NaN
4,NaN,NaN,Branca,Preta,Parda,Preta ou parda
5,Brasil,212650.323424,43.013008,9.075108,46.979981,56.055089
6,Norte,18577.619045,17.652349,7.473744,73.421972,80.895716
7,Rondônia,1804.543005,30.216115,8.235032,60.920943,69.155975
8,Acre,889.829002,15.587439,6.046421,77.040416,83.086837
9,Amazonas,4103.520007,14.343252,3.019257,80.135778,83.155035
10,Roraima,582.002001,20.588836,6.581009,67.817195,74.398204
11,Pará,8734.77202,16.618436,8.875837,73.505418,82.381255
12,Amapá,869.050004,15.040915,7.214187,77.265284,84.479471
13,Tocantins,1593.903005,19.117883,11.660672,67.763967,79.424639
14,Nordeste,57522.022114,24.669586,11.42573,63.146718,74.572448
15,Maranhão,7118.214015,16.997795,10.938734,71.239743,82.178477
16,Piauí,3288.504006,19.944566,8.397647,71.48792,79.885567
17,Ceará,9237.820018,25.544402,6.019584,67.666491,73.686075
18,Rio Grande do Norte,3560.903009,39.1464,8.275301,52.312423,60.587724
19,Paraíba,4038.225008,32.320926,7.157185,59.929329,67.086514
20,Pernambuco,9616.357021,31.198085,7.429437,60.44848,67.877917
21,Alagoas,3358.030008,28.269205,6.21424,64.567702,70.781942
22,Sergipe,2338.333004,21.99152,10.315805,67.345875,77.661681
23,Bahia,14965.636026,18.723439,21.471854,58.879481,80.351335
24,Sudeste,89611.153162,50.705709,9.574281,38.65795,48.232231
25,Minas Gerais,21401.130041,41.760881,10.344057,47.671703,58.01576
26,Espírito Santo,4104.647009,35.17451,12.25137,51.965548,64.216919
27,Rio de Janeiro,17462.80103,44.828756,14.212976,40.225419,54.438395
28,São Paulo,46642.575082,58.376974,7.248784,32.764196,40.01298
29,Sul,30358.784061,75.145761,4.350884,19.900269,24.251153
30,Paraná,11584.089024,65.526738,3.655889,29.797261,33.45315
31,Santa Catarina,7326.578015,81.503231,3.354458,14.694479,18.048937
32,Rio Grande do Sul,11448.117021,80.810372,5.691829,13.217334,18.909163
33,Centro-Oeste,16580.745043,34.655627,8.666632,55.826463,64.493095
34,Mato Grosso do Sul,2768.103008,42.995133,6.096721,49.599682,55.696404
35,Mato Grosso,3512.138009,29.440797,9.650145,59.795299,69.445444
36,Goiás,7208.837019,32.509622,8.253427,58.744707,66.998135
37,Distrito Federal,3091.667006,38.116797,10.813779,50.088498,60.902277
39,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN,NaN

In [73]:
# Droping all the rows that is not necessary(NaN or description)
rows_to_drop = [2, 3, 4, 5, 39]
df_cleaned = df_cleaned.drop(rows_to_drop)

# Renaming the columns name
df_cleaned.columns.values[1] = 'Quantity'
df_cleaned.columns.values[0] = 'r'

# Tranalating to English for better understanding 
new_column_names = {
    'Branca': 'White',
    'Preta': 'Black',
    'Parda': 'Mixed',
    'Preta ou parda': 'Black or Mixed',
    'Quantity': 'Quantity1(10^3)'
}

df_cleaned = df_cleaned.rename(columns = new_column_names)
df_cleaned

4,r,Quantity1(10^3),White,Black,Mixed,Black or Mixed
6,Norte,18577.619045,17.652349,7.473744,73.421972,80.895716
7,Rondônia,1804.543005,30.216115,8.235032,60.920943,69.155975
8,Acre,889.829002,15.587439,6.046421,77.040416,83.086837
9,Amazonas,4103.520007,14.343252,3.019257,80.135778,83.155035
10,Roraima,582.002001,20.588836,6.581009,67.817195,74.398204
11,Pará,8734.77202,16.618436,8.875837,73.505418,82.381255
12,Amapá,869.050004,15.040915,7.214187,77.265284,84.479471
13,Tocantins,1593.903005,19.117883,11.660672,67.763967,79.424639
14,Nordeste,57522.022114,24.669586,11.42573,63.146718,74.572448
15,Maranhão,7118.214015,16.997795,10.938734,71.239743,82.178477
16,Piauí,3288.504006,19.944566,8.397647,71.48792,79.885567
17,Ceará,9237.820018,25.544402,6.019584,67.666491,73.686075
18,Rio Grande do Norte,3560.903009,39.1464,8.275301,52.312423,60.587724
19,Paraíba,4038.225008,32.320926,7.157185,59.929329,67.086514
20,Pernambuco,9616.357021,31.198085,7.429437,60.44848,67.877917
21,Alagoas,3358.030008,28.269205,6.21424,64.567702,70.781942
22,Sergipe,2338.333004,21.99152,10.315805,67.345875,77.661681
23,Bahia,14965.636026,18.723439,21.471854,58.879481,80.351335
24,Sudeste,89611.153162,50.705709,9.574281,38.65795,48.232231
25,Minas Gerais,21401.130041,41.760881,10.344057,47.671703,58.01576
26,Espírito Santo,4104.647009,35.17451,12.25137,51.965548,64.216919
27,Rio de Janeiro,17462.80103,44.828756,14.212976,40.225419,54.438395
28,São Paulo,46642.575082,58.376974,7.248784,32.764196,40.01298
29,Sul,30358.784061,75.145761,4.350884,19.900269,24.251153
30,Paraná,11584.089024,65.526738,3.655889,29.797261,33.45315
31,Santa Catarina,7326.578015,81.503231,3.354458,14.694479,18.048937
32,Rio Grande do Sul,11448.117021,80.810372,5.691829,13.217334,18.909163
33,Centro-Oeste,16580.745043,34.655627,8.666632,55.826463,64.493095
34,Mato Grosso do Sul,2768.103008,42.995133,6.096721,49.599682,55.696404
35,Mato Grosso,3512.138009,29.440797,9.650145,59.795299,69.445444
36,Goiás,7208.837019,32.509622,8.253427,58.744707,66.998135
37,Distrito Federal,3091.667006,38.116797,10.813779,50.088498,60.902277

In [74]:
# Create a dictionary mapping Brazilian states and regions to their respective regions
Region = {
    'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
    'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
    'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
    'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
    'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
}

# Create a new column 'Region' in the DataFrame 'df_cleaned'
# Use the 'apply' function to map the state names in column 'r'(region) to their respective regions based on the 'Region' dictionary
# If the state name is in the 'Region' dictionary, assign the corresponding region; otherwise, keep the state name as is
df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)

# Create a new column 'State' in the DataFrame 'df_cleaned'
# Use the 'apply' function to check if the state name in column 'r' is present in the 'Region' dictionary
# If the state name is in the dictionary, keep it; otherwise, assign an empty string
df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')

# Drop the original column 'r' from the DataFrame 'df_cleaned' as it is no longer needed
df_cleaned = df_cleaned.drop(columns = 'r')
df_cleaned

4,Quantity1(10^3),White,Black,Mixed,Black or Mixed,Region,State
6,18577.619045,17.652349,7.473744,73.421972,80.895716,Norte,Norte
7,1804.543005,30.216115,8.235032,60.920943,69.155975,Norte,Rondônia
8,889.829002,15.587439,6.046421,77.040416,83.086837,Norte,Acre
9,4103.520007,14.343252,3.019257,80.135778,83.155035,Norte,Amazonas
10,582.002001,20.588836,6.581009,67.817195,74.398204,Norte,Roraima
11,8734.77202,16.618436,8.875837,73.505418,82.381255,Norte,Pará
12,869.050004,15.040915,7.214187,77.265284,84.479471,Norte,Amapá
13,1593.903005,19.117883,11.660672,67.763967,79.424639,Norte,Tocantins
14,57522.022114,24.669586,11.42573,63.146718,74.572448,Nordeste,Nordeste
15,7118.214015,16.997795,10.938734,71.239743,82.178477,Nordeste,Maranhão
16,3288.504006,19.944566,8.397647,71.48792,79.885567,Nordeste,Piauí
17,9237.820018,25.544402,6.019584,67.666491,73.686075,Nordeste,Ceará
18,3560.903009,39.1464,8.275301,52.312423,60.587724,Nordeste,Rio Grande do Norte
19,4038.225008,32.320926,7.157185,59.929329,67.086514,Nordeste,Paraíba
20,9616.357021,31.198085,7.429437,60.44848,67.877917,Nordeste,Pernambuco
21,3358.030008,28.269205,6.21424,64.567702,70.781942,Nordeste,Alagoas
22,2338.333004,21.99152,10.315805,67.345875,77.661681,Nordeste,Sergipe
23,14965.636026,18.723439,21.471854,58.879481,80.351335,Nordeste,Bahia
24,89611.153162,50.705709,9.574281,38.65795,48.232231,Sudeste,Sudeste
25,21401.130041,41.760881,10.344057,47.671703,58.01576,Sudeste,Minas Gerais
26,4104.647009,35.17451,12.25137,51.965548,64.216919,Sudeste,Espírito Santo
27,17462.80103,44.828756,14.212976,40.225419,54.438395,Sudeste,Rio de Janeiro
28,46642.575082,58.376974,7.248784,32.764196,40.01298,Sudeste,São Paulo
29,30358.784061,75.145761,4.350884,19.900269,24.251153,Sul,Sul
30,11584.089024,65.526738,3.655889,29.797261,33.45315,Sul,Paraná
31,7326.578015,81.503231,3.354458,14.694479,18.048937,Sul,Santa Catarina
32,11448.117021,80.810372,5.691829,13.217334,18.909163,Sul,Rio Grande do Sul
33,16580.745043,34.655627,8.666632,55.826463,64.493095,Centro-Oeste,Centro-Oeste
34,2768.103008,42.995133,6.096721,49.599682,55.696404,Centro-Oeste,Mato Grosso do Sul
35,3512.138009,29.440797,9.650145,59.795299,69.445444,Centro-Oeste,Mato Grosso
36,7208.837019,32.509622,8.253427,58.744707,66.998135,Centro-Oeste,Goiás
37,3091.667006,38.116797,10.813779,50.088498,60.902277,Centro-Oeste,Distrito Federal

In [75]:
# To transform Columns into row, by keeping the columns(Region, State, and Quantity1(10^3)
# And the rows values to be (White, Black, Mixed and Black ot Mixed) in the Race column to their respective percentage
df_cleaned = df_cleaned.melt(id_vars=['Region', 'State', 'Quantity1(10^3)'], 
                    value_vars = ['White', 'Black', 'Mixed', 'Black or Mixed'],
                    var_name = 'Race',  
                    value_name = 'Percentage')

# Creating a Year column   
df_cleaned['Year'] = 2021
df_cleaned

,Region,State,Quantity1(10^3),Race,Percentage,Year
0,Norte,Norte,18577.619045,White,17.652349,2021
1,Norte,Rondônia,1804.543005,White,30.216115,2021
2,Norte,Acre,889.829002,White,15.587439,2021
3,Norte,Amazonas,4103.520007,White,14.343252,2021
4,Norte,Roraima,582.002001,White,20.588836,2021
...,...,...,...,...,...,...
123,Centro-Oeste,Centro-Oeste,16580.745043,Black or Mixed,64.493095,2021
124,Centro-Oeste,Mato Grosso do Sul,2768.103008,Black or Mixed,55.696404,2021
125,Centro-Oeste,Mato Grosso,3512.138009,Black or Mixed,69.445444,2021
126,Centro-Oeste,Goiás,7208.837019,Black or Mixed,66.998135,2021
127,Centro-Oeste,Distrito Federal,3091.667006,Black or Mixed,60.902277,2021

In [76]:
# The percentage of the population was based on region and state, therefore I got the actual quantity for each race and State
df_cleaned['Quantity(10^3)'] = (df_cleaned['Quantity1(10^3)'] * df_cleaned['Percentage']) / 100

columns_to_drop = ['Quantity1(10^3)', 'Percentage']
df_cleaned = df_cleaned.drop(columns = columns_to_drop)

# Rounding the quantity
df_cleaned['Quantity(10^3)'] = df_cleaned['Quantity(10^3)'].round().astype(int)

# Translating into english for better understanding
translation_dict = {
        'Norte': 'North',
        'Nordeste': 'Northeast',
        'Sudeste': 'Southeast',
        'Sul': 'South',
        'Centro-Oeste': 'Central-West'
    }

# Replace Portuguese region names with English names in the 'Region' column
df_cleaned['Region'] = df_cleaned['Region'].replace(translation_dict)

df_cleaned

           Region               State            Race  Year  Quantity(10^3)
0           North               Norte           White  2021            3279
1           North            Rondônia           White  2021             545
2           North                Acre           White  2021             138
3           North            Amazonas           White  2021             588
4           North             Roraima           White  2021             119
..            ...                 ...             ...   ...             ...
123  Central-West        Centro-Oeste  Black or Mixed  2021           10693
124  Central-West  Mato Grosso do Sul  Black or Mixed  2021            1541
125  Central-West         Mato Grosso  Black or Mixed  2021            2439
126  Central-West               Goiás  Black or Mixed  2021            4829
127  Central-West    Distrito Federal  Black or Mixed  2021            1882

[128 rows x 5 columns]

In [77]:
# Is going to be the same cleaning process, however there is multiple years to automate
# The code above was to test and check if the Data Frame was clean and ready to use
def process_population_data(file_path, sheet_name):

    # Read the Excel file and load the specified sheet into a DataFrame
    df_Demographic_Distribution = pd.read_excel(file_path, sheet_name = sheet_name)
    df_cleaned = df_Demographic_Distribution.copy()
    df_cleaned = df_cleaned.dropna(how = 'all')
    df_cleaned.columns = df_cleaned.iloc[2]

    rows_to_drop = [2, 3, 4, 5, 39]
    df_cleaned = df_cleaned.drop(rows_to_drop)
    df_cleaned.columns.values[1] = 'Quantity'
    df_cleaned.columns.values[0] = 'r'

    new_column_names = {
        'Branca': 'White',
        'Preta': 'Black',
        'Parda': 'Mixed',
        'Preta ou parda': 'Black or Mixed',
        'Quantity': 'Quantity1(10^3)'
    }

    df_cleaned = df_cleaned.rename(columns = new_column_names)



    Region = {
        'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
        'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
        'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
        'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
        'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
    }


    df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)
    df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')
    df_cleaned = df_cleaned.drop(columns = 'r')


    df_cleaned = df_cleaned.melt(id_vars=['Region', 'State', 'Quantity1(10^3)'], 
                    value_vars = ['White', 'Black', 'Mixed', 'Black or Mixed'],
                    var_name = 'Race',  
                    value_name ='Percentage')
    
    # Return the reshaped DataFrame
    return df_cleaned

    

def combine_data(file_path, years):

    # Initialize an empty DataFrame to store combined data
    combined_df = pd.DataFrame()

    # Iterate over each year provided in the 'years' list
    for year in years:

        # Convert year to string to match sheet names
        sheet_name = str(year)

        # Process the data for the given year
        df_year = process_population_data(file_path, sheet_name)

        # Add a new column 'Year' to the DataFrame
        df_year['Year'] = year

        # Concatenate the current year's data with the combined DataFrame
        combined_df = pd.concat([combined_df, df_year], ignore_index=True)
        
    # Return the combined DataFrame containing data for all specified years
    return combined_df


file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 1.1 (Pop_Geo).xls'
years = [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]
df_cleaned = combine_data(file_path, years)


df_cleaned['Quantity(10^3)'] = (df_cleaned['Quantity1(10^3)'] * df_cleaned['Percentage']) / 100

columns_to_drop = ['Quantity1(10^3)', 'Percentage']
df_cleaned = df_cleaned.drop(columns = columns_to_drop)


df_cleaned['Quantity(10^3)'] = df_cleaned['Quantity(10^3)'].round().astype(int)

translation_dict = {
        'Norte': 'North',
        'Nordeste': 'Northeast',
        'Sudeste': 'Southeast',
        'Sul': 'South',
        'Centro-Oeste': 'Central-West'
    }


df_cleaned['Region'] = df_cleaned['Region'].replace(translation_dict)
df_cleaned

            Region               State            Race  Year  Quantity(10^3)
0            North               Norte           White  2021            3279
1            North            Rondônia           White  2021             545
2            North                Acre           White  2021             138
3            North            Amazonas           White  2021             588
4            North             Roraima           White  2021             119
...            ...                 ...             ...   ...             ...
1275  Central-West        Centro-Oeste  Black or Mixed  2012            8762
1276  Central-West  Mato Grosso do Sul  Black or Mixed  2012            1268
1277  Central-West         Mato Grosso  Black or Mixed  2012            2000
1278  Central-West               Goiás  Black or Mixed  2012            3916
1279  Central-West    Distrito Federal  Black or Mixed  2012            1576

[1280 rows x 5 columns]

In [84]:
# Getting the percentage of race in each region
# Filtering for State and Race
df_Distribution_only_region = df_cleaned.copy()

# Specifying that I dont want the states
State_to_keep = ['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste']
df_Distribution_only_region = df_Distribution_only_region[df_Distribution_only_region['State'].isin(State_to_keep)] 

# Eliminating 'Black and Mixed'
race_that_want = ['White', 'Black', 'Mixed']
df_Distribution_only_region = df_Distribution_only_region[df_Distribution_only_region['Race'].isin(race_that_want)]

df_Distribution_only_region

            Region         State   Race  Year  Quantity(10^3)
0            North         Norte  White  2021            3279
8        Northeast      Nordeste  White  2021           14190
18       Southeast       Sudeste  White  2021           45437
23           South           Sul  White  2021           22813
27    Central-West  Centro-Oeste  White  2021            5746
...            ...           ...    ...   ...             ...
1216         North         Norte  Mixed  2012           11868
1224     Northeast      Nordeste  Mixed  2012           35366
1234     Southeast       Sudeste  Mixed  2012           30400
1239         South           Sul  Mixed  2012            4736
1243  Central-West  Centro-Oeste  Mixed  2012            7822

[150 rows x 5 columns]

In [85]:
# Calculating the percentage by race in each region

# Grouping by Region and Year and summing them
group = df_Distribution_only_region.groupby(['Region', 'Year'])['Quantity(10^3)'].transform('sum')

# Inserting the result from the variable 'group' into a new column in the Data Frame
df_Distribution_only_region['Total'] = group
df_Distribution_only_region

            Region         State   Race  Year  Quantity(10^3)  Total
0            North         Norte  White  2021            3279  18307
8        Northeast      Nordeste  White  2021           14190  57085
18       Southeast       Sudeste  White  2021           45437  88657
23           South           Sul  White  2021           22813  30174
27    Central-West  Centro-Oeste  White  2021            5746  16438
...            ...           ...    ...   ...             ...    ...
1216         North         Norte  Mixed  2012           11868  16290
1224     Northeast      Nordeste  Mixed  2012           35366  54504
1234     Southeast       Sudeste  Mixed  2012           30400  82836
1239         South           Sul  Mixed  2012            4736  28136
1243  Central-West  Centro-Oeste  Mixed  2012            7822  14555

[150 rows x 6 columns]

In [86]:
# Now dividing the quantity of each race to the 'total' column, to obtaing the actual percentage
# For example the north region has 17% white people and in northeast has 25% of them and so on.
df_Distribution_only_region['Percentage'] = (df_Distribution_only_region['Quantity(10^3)'] / df_Distribution_only_region['Total']) * 100
df_Distribution_only_region = df_Distribution_only_region.drop(columns = ['State', 'Total'])
df_Distribution_only_region

            Region   Race  Year  Quantity(10^3)  Percentage
0            North  White  2021            3279   17.911182
8        Northeast  White  2021           14190   24.857668
18       Southeast  White  2021           45437   51.250324
23           South  White  2021           22813   75.604825
27    Central-West  White  2021            5746   34.955591
...            ...    ...   ...             ...         ...
1216         North  Mixed  2012           11868   72.854512
1224     Northeast  Mixed  2012           35366   64.886981
1234     Southeast  Mixed  2012           30400   36.699020
1239         South  Mixed  2012            4736   16.832528
1243  Central-West  Mixed  2012            7822   53.740982

[150 rows x 5 columns]