In [45]:
import pandas as pd
import numpy as np

# Importing the Data Frame from IBGE
file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 2.5 (Rend_Form_Geo).xls'
df_Financial = pd.read_excel(file_path, sheet_name = '2021')
df_cleaned = df_Financial.copy()

# Dropping all the Unnecessary rows (Description and Nan Values)
Rows_to_drop = [1, 2, 3, 66, 67, 68, 69, 70, 71, 72]
df_cleaned = df_cleaned.drop(Rows_to_drop)
df_cleaned = df_cleaned.dropna(how ='all')
df_cleaned

,"Tabela 2.5 - Rendimento médio real habitual do trabalho principal das pessoas de 14 anos ou mais de idade, ocupadas na semana de referência e em ocupações formais e informais, por cor ou raça, segundo as Grandes Regiões, as Unidades da Federação e os Municípios das Capitais - Brasil - 2021",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
4,NaN,NaN,Branca,Preta,Parda,Preta ou parda,NaN,Branca,Preta,Parda,Preta ou parda,NaN,Branca,Preta,Parda,Preta ou parda
6,Brasil,2405.758521,3098.914988,1764.399163,1813.586869,1804.419788,2950.64817,3526.191595,2200.076297,2343.946273,2315.894427,1542.971162,2157.095221,1175.605525,1182.067558,1180.931065
7,Norte,1812.330803,2477.968905,1594.682749,1657.891051,1651.11106,2586.98757,3339.416263,2309.993957,2372.072491,2365.634782,1210.883313,1613.273445,1102.055172,1133.218685,1129.794974
8,Rondônia,1998.084135,2209.917314,2052.663814,1872.589876,1891.016418,2316.812492,2530.350741,2677.889156,2154.433581,2204.592923,1534.985163,1712.373402,1295.525078,1468.469507,1449.18759
9,Porto Velho,2246.722705,2728.124723,2080.593716,2101.311005,2099.384651,2729.389646,3346.27011,2686.587277,2540.452636,2552.999819,1513.694467,1809.424248,1312.382777,1414.016755,1403.455959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Cuiabá,2857.507299,3845.162329,2501.281404,2347.65935,2386.552571,3416.164428,4244.755456,3005.156434,2901.31206,2926.196944,1949.283869,2785.256234,1898.598663,1564.478607,1655.19976
62,Goiás,2214.805875,2629.660891,1858.346611,2045.045929,2019.191162,2581.458879,3042.607139,2225.673004,2371.786029,2352.165729,1703.155356,2011.774112,1394.80011,1597.214843,1568.03137
63,Goiânia,2881.122669,3691.209322,2125.611099,2460.257268,2415.225892,3270.508236,4041.354706,2395.268793,2873.770195,2803.540618,2254.397983,3087.231033,1597.506787,1844.182056,1815.637389
64,Distrito Federal,4083.771826,5364.635021,2759.948258,3375.06529,3250.26101,4889.122409,6479.864521,3082.684223,3973.174141,3792.113828,2232.430437,2472.364584,2069.758008,2106.599992,2099.158699
65,Brasília,4083.771826,5364.635021,2759.948258,3375.06529,3250.26101,4889.122409,6479.864521,3082.684223,3973.174141,3792.113828,2232.430437,2472.364584,2069.758008,2106.599992,2099.158699

In [46]:
# Reanaming the columns for better organization, easier to melt after
rename_dict = {
    'Unnamed: 2':'Branca',
    'Unnamed: 3':'Preta',
    'Unnamed: 4':'Parda',
    'Unnamed: 5':'Preta ou parda',
    'Unnamed: 7': 'Branca.1',
    'Unnamed: 8': 'Preta.1',
    'Unnamed: 9': 'Parda.1',
    'Unnamed: 10': 'Preta ou parda.1',
    'Unnamed: 12': 'Branca.2',
    'Unnamed: 13': 'Preta.2',
    'Unnamed: 14': 'Parda.2',
    'Unnamed: 15': 'Preta ou parda.2'
}

# Rename columns using the dictionary
df_cleaned = df_cleaned.rename(columns = rename_dict)

# Renaming the first column to 'r'(race)
df_cleaned.columns.values[0] = 'r'

# Dropping these columns because, is the total of the salary which I am not interested to use them
columns_to_drop = ['Unnamed: 1', 'Unnamed: 6', 'Unnamed: 11']
df_cleaned = df_cleaned.drop(columns = columns_to_drop)

# Again not necessary rows
Rows_to_drop = [4, 6]
df_cleaned = df_cleaned.drop(Rows_to_drop)
df_cleaned

,r,Branca,Preta,Parda,Preta ou parda,Branca.1,Preta.1,Parda.1,Preta ou parda.1,Branca.2,Preta.2,Parda.2,Preta ou parda.2
7,Norte,2477.968905,1594.682749,1657.891051,1651.11106,3339.416263,2309.993957,2372.072491,2365.634782,1613.273445,1102.055172,1133.218685,1129.794974
8,Rondônia,2209.917314,2052.663814,1872.589876,1891.016418,2530.350741,2677.889156,2154.433581,2204.592923,1712.373402,1295.525078,1468.469507,1449.18759
9,Porto Velho,2728.124723,2080.593716,2101.311005,2099.384651,3346.27011,2686.587277,2540.452636,2552.999819,1809.424248,1312.382777,1414.016755,1403.455959
10,Acre,2497.616416,1926.745276,1777.629536,1791.323731,3035.120614,2593.596736,2446.293283,2459.689327,1955.376613,1377.401652,1215.818347,1230.778691
11,Rio Branco,2709.000359,1842.019423,2009.226939,1987.840537,3302.181893,2363.422176,2491.561154,2475.521315,2053.274851,1249.321277,1430.806661,1407.004404
12,Amazonas,2501.462149,1670.925439,1654.187223,1654.954987,3335.421953,2263.795785,2353.365587,2348.555108,1769.676417,1117.763973,1170.621674,1168.487709
13,Manaus,2857.506485,1811.659522,1963.081924,1955.207686,3519.569749,2298.293418,2506.235353,2493.840607,2113.458325,1120.649866,1402.707298,1390.289518
14,Roraima,3560.763114,1568.45657,1971.207784,1924.860527,4786.12452,2146.199484,2712.098805,2643.324911,2222.979891,1007.417808,1332.152401,1296.615584
15,Boa Vista,3941.038172,1559.935053,2099.02565,2036.544739,5136.504155,2122.16838,2798.804267,2720.945976,2497.841617,1020.612483,1416.897507,1370.646343
16,Pará,2385.274192,1401.183623,1532.245198,1515.359031,3549.676457,2202.167971,2337.711344,2321.981442,1386.674418,986.128445,1029.074336,1023.205966
17,Belém,4285.799504,2131.008436,2337.244289,2307.70614,5822.181017,3129.566541,3425.182166,3383.796692,1821.931579,1137.28336,1194.848872,1186.410448
18,Amapá,2416.321856,2288.646277,1831.430103,1873.68383,3397.782919,3085.384279,2866.12703,2892.703143,1305.827931,1367.279808,1153.332859,1168.843685
19,Macapá,2599.116985,2364.452274,2035.040424,2065.474876,3724.454542,3244.68147,3037.129893,3060.749865,1341.765181,1295.474266,1264.382325,1266.720615
20,Tocantins,2957.415961,1763.586284,1852.899847,1838.448253,3788.152107,2099.243367,2472.76461,2413.257354,2035.955309,1460.642615,1273.234958,1303.993329
21,Palmas,4374.532228,2317.011501,2366.734217,2359.996414,6326.807302,2664.370734,2767.176558,2751.534262,1948.683185,1655.530981,1830.018736,1810.451057
22,Nordeste,2233.878833,1396.607032,1470.092498,1456.705294,3158.723002,1944.736298,2180.442943,2134.042475,1294.531443,903.102578,932.960772,927.86363
23,Maranhão,1991.761084,1282.288012,1339.876422,1330.240167,2803.138836,1982.782469,2111.763535,2089.98847,1337.438225,899.346927,924.802992,920.563943
24,São Luís,2508.539904,1598.963614,1923.932953,1862.346449,3413.896641,2294.7744,2635.215399,2571.293597,1591.029067,960.330993,1256.522988,1199.905038
25,Piauí,1847.185158,1450.54656,1282.189445,1304.500905,3021.770709,2324.023971,2089.022181,2124.325335,938.242911,792.8597,805.90806,804.319743
26,Teresina,2817.7176,1980.194241,1598.752535,1670.723271,3627.627563,2514.325095,2007.852436,2109.062186,1593.675948,1241.041125,1117.382776,1139.042071
27,Ceará,2064.037318,1492.239017,1655.021154,1639.246089,2486.556362,1996.981974,2411.373782,2369.912525,1655.541194,1065.155104,1054.977111,1055.937904
28,Fortaleza,3005.549693,1543.023277,2272.144982,2190.18441,2983.260471,1858.820146,2983.993911,2856.816779,3040.528374,1150.235449,1398.91005,1371.145622
29,Rio Grande do Norte,2439.289329,1557.112555,1797.259394,1758.235202,3199.131678,2106.614812,2749.628252,2627.41852,1364.138881,769.978405,893.370803,876.767679
30,Natal,3284.118068,1785.618446,1951.465207,1929.106938,3398.240733,2215.77171,2452.342571,2415.578215,2967.707138,1007.828657,1350.83545,1313.53162
31,Paraíba,2283.740113,1213.436145,1464.792019,1435.743336,3531.544093,1572.885969,2175.82764,2094.1325,1004.521708,809.632018,903.657974,894.332291
32,João Pessoa,3910.262493,1356.391317,2207.711309,2055.263095,5098.169905,1509.833596,2560.73589,2362.326229,1659.881617,1031.827821,1589.864181,1499.754502
33,Pernambuco,2378.584092,1695.858645,1404.621523,1447.268679,3556.874938,2542.721847,2044.707215,2125.573245,1069.658112,855.235978,899.956877,893.989739
34,Recife,3506.695911,2884.872557,2026.413306,2212.210259,4392.733412,3999.371988,2746.875261,3035.607396,1387.799213,1083.199711,1072.887867,1074.91892
35,Alagoas,1977.577169,1346.697132,1448.577761,1437.734271,2642.364472,1846.148831,2052.25628,2030.889583,1123.862663,920.481328,904.168655,905.945312
36,Maceió,2693.276732,1271.954248,1772.41181,1701.962657,3251.833636,1635.984204,2468.879883,2363.786669,1556.647327,939.490547,949.591655,948.001819
37,Sergipe,2554.023096,1496.567648,1525.308817,1520.757381,3771.784646,2184.153069,2206.524143,2202.660134,1377.259559,774.308354,941.083445,916.79478
38,Aracaju,4810.913775,2078.730947,2268.506866,2237.91957,5461.505797,2534.539013,2996.996742,2912.195222,3244.47659,1089.32628,1238.123883,1219.131389
39,Bahia,2296.31188,1316.773918,1411.866855,1382.972062,3289.216644,1737.346604,2028.18868,1933.851916,1426.294415,922.570594,927.820094,926.314192
40,Salvador,4179.066657,1702.567672,2178.460082,1964.844641,5127.26284,2074.20279,2479.359233,2306.431426,1931.197507,1160.209784,1622.01708,1397.816087
41,Sudeste,3444.053412,1915.625774,1978.70883,1964.866004,3801.789113,2250.763907,2357.757125,2334.111529,2592.480095,1327.829118,1330.225079,1329.705755
42,Minas Gerais,2566.633217,1708.922841,1769.158005,1757.217176,3012.81815,2060.256539,2093.608628,2086.914006,1722.840345,1116.602158,1244.304033,1219.507181
43,Belo Horizonte,4406.393073,2096.26647,2729.90054,2581.666973,4932.815503,2459.289941,3039.440127,2907.872766,3056.114011,1308.079597,1961.362516,1797.284333
44,Espírito Santo,2689.551326,1706.977885,1884.611869,1844.730394,2955.330957,1898.270193,2208.374135,2137.067279,2222.085474,1399.00233,1402.854966,1402.021673
45,Vitória,5558.62268,2160.396836,3487.496631,3120.080612,5647.211084,2660.275297,4467.090279,3989.685036,5293.89699,1346.524432,1582.049924,1511.339415
46,Rio de Janeiro,3922.515337,1978.662038,2116.505069,2077.596527,4396.617572,2463.789637,2669.805105,2610.338506,2860.824936,1225.537286,1322.023215,1295.692487
47,Rio de Janeiro,5011.148544,2414.275684,2645.504106,2579.444414,5523.104151,2931.256629,3317.244229,3201.480175,3761.650955,1386.315111,1543.966365,1502.80884
48,São Paulo,3640.794436,2034.809732,2069.997474,2062.808598,3921.583903,2289.389425,2421.932243,2394.769117,2892.749852,1533.753521,1385.311229,1415.453413
49,São Paulo,4949.802907,2111.201266,2370.618865,2315.113,5313.348795,2413.976473,2776.482042,2701.624789,4111.464085,1574.575194,1551.445657,1556.733258
50,Sul,2835.266346,1968.420658,1956.055091,1958.518551,3073.833023,2163.78776,2210.551105,2200.879171,2046.90356,1454.260549,1385.96543,1398.370277
51,Paraná,2906.083898,2129.415852,1882.467937,1916.131693,3175.991627,2337.817317,2166.960525,2190.937712,2084.211406,1643.926179,1287.590337,1333.130003
52,Curitiba,3912.611856,3046.920573,2565.940148,2654.64789,4184.146544,3805.633461,2803.262192,2973.755507,3038.190395,1258.037809,1749.538737,1636.398918
53,Santa Catarina,2778.160793,1864.972785,2139.653539,2084.265108,2931.147554,1977.482971,2265.946152,2207.630998,2135.877131,1484.080039,1717.980756,1671.216043
54,Florianópolis,4875.844784,1798.672368,2932.278493,2283.363494,5112.950614,1898.564495,3057.262125,2362.540175,3791.904688,1355.934313,2595.144978,2004.30322
55,Rio Grande do Sul,2815.840794,1887.862349,1977.814671,1950.088725,3093.656021,2118.714487,2259.131249,2213.257508,1969.424441,1283.319039,1420.564842,1383.716464
56,Porto Alegre,4518.05039,2395.397311,2453.478766,2428.645381,5108.778434,2601.680606,2907.764775,2765.030796,2833.346196,1727.625341,1598.368454,1641.916057
57,Centro-Oeste,3355.345733,2177.383264,2302.388674,2283.346451,4000.950471,2607.600578,2705.274811,2690.774628,2157.311854,1574.198021,1693.837373,1674.91996
58,Mato Grosso do Sul,3044.417976,2237.382718,1991.678583,2025.404266,3549.693092,2780.960617,2400.295554,2453.883367,2041.450686,1409.555689,1412.880825,1412.441122
59,Campo Grande,3791.913042,2272.306093,2233.957774,2240.353666,4540.066573,2701.008293,2808.86665,2789.43609,2289.283416,1558.559233,1474.582495,1487.04873
60,Mato Grosso,2976.847107,2110.500649,2233.300396,2214.904669,3294.468164,2581.450987,2493.169467,2504.77844,2361.409502,1606.346879,1840.774197,1799.507582
61,Cuiabá,3845.162329,2501.281404,2347.65935,2386.552571,4244.755456,3005.156434,2901.31206,2926.196944,2785.256234,1898.598663,1564.478607,1655.19976
62,Goiás,2629.660891,1858.346611,2045.045929,2019.191162,3042.607139,2225.673004,2371.786029,2352.165729,2011.774112,1394.80011,1597.214843,1568.03137
63,Goiânia,3691.209322,2125.611099,2460.257268,2415.225892,4041.354706,2395.268793,2873.770195,2803.540618,3087.231033,1597.506787,1844.182056,1815.637389
64,Distrito Federal,5364.635021,2759.948258,3375.06529,3250.26101,6479.864521,3082.684223,3973.174141,3792.113828,2472.364584,2069.758008,2106.599992,2099.158699
65,Brasília,5364.635021,2759.948258,3375.06529,3250.26101,6479.864521,3082.684223,3973.174141,3792.113828,2472.364584,2069.758008,2106.599992,2099.158699

In [47]:
# Create a dictionary mapping Brazilian states and regions to their respective regions
Region = {
    'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
    'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
    'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
    'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
    'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
}

# Create a new column 'Region' in the DataFrame 'df_cleaned'
# Use the 'apply' function to map the state names in column 'r'(race) to their respective regions based on the 'Region' dictionary
# If the state name is in the 'Region' dictionary, assign the corresponding region; otherwise, keep the state name as is
df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)

# Create a new column 'State' in the DataFrame 'df_cleaned'
# Use the 'apply' function to check if the state name in column 'r' is present in the 'Region' dictionary
# If the state name is in the dictionary, keep it; otherwise, assign an empty string
df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')

# Drop the original column 'r' from the DataFrame 'df_cleaned' as it is no longer needed
df_cleaned = df_cleaned.drop(columns = 'r')

# These respective cities is not a Region so I dropped the rows that have them, 'Brasil' is the total of everything
region_to_drop = ['Brasil', 'Porto Velho', 'Rio Branco', 'Manaus', 'Boa Vista', 'Belém', 'Macapá', 'Palmas', 'São Luís', 'Teresina', 'Fortaleza', 'Natal', 'João Pessoa', 'Recife', 'Maceió', 'Aracaju', 'Salvador', 'Belo Horizonte', 'Vitória', 'Curitiba', 'Florianópolis', 'Porto Alegre', 'Campo Grande', 'Cuiabá', 'Goiânia', 'Brasília']
df_cleaned = df_cleaned[~df_cleaned['Region'].isin(region_to_drop)]
df_cleaned

,Branca,Preta,Parda,Preta ou parda,Branca.1,Preta.1,Parda.1,Preta ou parda.1,Branca.2,Preta.2,Parda.2,Preta ou parda.2,Region,State
7,2477.968905,1594.682749,1657.891051,1651.11106,3339.416263,2309.993957,2372.072491,2365.634782,1613.273445,1102.055172,1133.218685,1129.794974,Norte,Norte
8,2209.917314,2052.663814,1872.589876,1891.016418,2530.350741,2677.889156,2154.433581,2204.592923,1712.373402,1295.525078,1468.469507,1449.18759,Norte,Rondônia
10,2497.616416,1926.745276,1777.629536,1791.323731,3035.120614,2593.596736,2446.293283,2459.689327,1955.376613,1377.401652,1215.818347,1230.778691,Norte,Acre
12,2501.462149,1670.925439,1654.187223,1654.954987,3335.421953,2263.795785,2353.365587,2348.555108,1769.676417,1117.763973,1170.621674,1168.487709,Norte,Amazonas
14,3560.763114,1568.45657,1971.207784,1924.860527,4786.12452,2146.199484,2712.098805,2643.324911,2222.979891,1007.417808,1332.152401,1296.615584,Norte,Roraima
16,2385.274192,1401.183623,1532.245198,1515.359031,3549.676457,2202.167971,2337.711344,2321.981442,1386.674418,986.128445,1029.074336,1023.205966,Norte,Pará
18,2416.321856,2288.646277,1831.430103,1873.68383,3397.782919,3085.384279,2866.12703,2892.703143,1305.827931,1367.279808,1153.332859,1168.843685,Norte,Amapá
20,2957.415961,1763.586284,1852.899847,1838.448253,3788.152107,2099.243367,2472.76461,2413.257354,2035.955309,1460.642615,1273.234958,1303.993329,Norte,Tocantins
22,2233.878833,1396.607032,1470.092498,1456.705294,3158.723002,1944.736298,2180.442943,2134.042475,1294.531443,903.102578,932.960772,927.86363,Nordeste,Nordeste
23,1991.761084,1282.288012,1339.876422,1330.240167,2803.138836,1982.782469,2111.763535,2089.98847,1337.438225,899.346927,924.802992,920.563943,Nordeste,Maranhão
25,1847.185158,1450.54656,1282.189445,1304.500905,3021.770709,2324.023971,2089.022181,2124.325335,938.242911,792.8597,805.90806,804.319743,Nordeste,Piauí
27,2064.037318,1492.239017,1655.021154,1639.246089,2486.556362,1996.981974,2411.373782,2369.912525,1655.541194,1065.155104,1054.977111,1055.937904,Nordeste,Ceará
29,2439.289329,1557.112555,1797.259394,1758.235202,3199.131678,2106.614812,2749.628252,2627.41852,1364.138881,769.978405,893.370803,876.767679,Nordeste,Rio Grande do Norte
31,2283.740113,1213.436145,1464.792019,1435.743336,3531.544093,1572.885969,2175.82764,2094.1325,1004.521708,809.632018,903.657974,894.332291,Nordeste,Paraíba
33,2378.584092,1695.858645,1404.621523,1447.268679,3556.874938,2542.721847,2044.707215,2125.573245,1069.658112,855.235978,899.956877,893.989739,Nordeste,Pernambuco
35,1977.577169,1346.697132,1448.577761,1437.734271,2642.364472,1846.148831,2052.25628,2030.889583,1123.862663,920.481328,904.168655,905.945312,Nordeste,Alagoas
37,2554.023096,1496.567648,1525.308817,1520.757381,3771.784646,2184.153069,2206.524143,2202.660134,1377.259559,774.308354,941.083445,916.79478,Nordeste,Sergipe
39,2296.31188,1316.773918,1411.866855,1382.972062,3289.216644,1737.346604,2028.18868,1933.851916,1426.294415,922.570594,927.820094,926.314192,Nordeste,Bahia
41,3444.053412,1915.625774,1978.70883,1964.866004,3801.789113,2250.763907,2357.757125,2334.111529,2592.480095,1327.829118,1330.225079,1329.705755,Sudeste,Sudeste
42,2566.633217,1708.922841,1769.158005,1757.217176,3012.81815,2060.256539,2093.608628,2086.914006,1722.840345,1116.602158,1244.304033,1219.507181,Sudeste,Minas Gerais
44,2689.551326,1706.977885,1884.611869,1844.730394,2955.330957,1898.270193,2208.374135,2137.067279,2222.085474,1399.00233,1402.854966,1402.021673,Sudeste,Espírito Santo
46,3922.515337,1978.662038,2116.505069,2077.596527,4396.617572,2463.789637,2669.805105,2610.338506,2860.824936,1225.537286,1322.023215,1295.692487,Sudeste,Rio de Janeiro
47,5011.148544,2414.275684,2645.504106,2579.444414,5523.104151,2931.256629,3317.244229,3201.480175,3761.650955,1386.315111,1543.966365,1502.80884,Sudeste,Rio de Janeiro
48,3640.794436,2034.809732,2069.997474,2062.808598,3921.583903,2289.389425,2421.932243,2394.769117,2892.749852,1533.753521,1385.311229,1415.453413,Sudeste,São Paulo
49,4949.802907,2111.201266,2370.618865,2315.113,5313.348795,2413.976473,2776.482042,2701.624789,4111.464085,1574.575194,1551.445657,1556.733258,Sudeste,São Paulo
50,2835.266346,1968.420658,1956.055091,1958.518551,3073.833023,2163.78776,2210.551105,2200.879171,2046.90356,1454.260549,1385.96543,1398.370277,Sul,Sul
51,2906.083898,2129.415852,1882.467937,1916.131693,3175.991627,2337.817317,2166.960525,2190.937712,2084.211406,1643.926179,1287.590337,1333.130003,Sul,Paraná
53,2778.160793,1864.972785,2139.653539,2084.265108,2931.147554,1977.482971,2265.946152,2207.630998,2135.877131,1484.080039,1717.980756,1671.216043,Sul,Santa Catarina
55,2815.840794,1887.862349,1977.814671,1950.088725,3093.656021,2118.714487,2259.131249,2213.257508,1969.424441,1283.319039,1420.564842,1383.716464,Sul,Rio Grande do Sul
57,3355.345733,2177.383264,2302.388674,2283.346451,4000.950471,2607.600578,2705.274811,2690.774628,2157.311854,1574.198021,1693.837373,1674.91996,Centro-Oeste,Centro-Oeste
58,3044.417976,2237.382718,1991.678583,2025.404266,3549.693092,2780.960617,2400.295554,2453.883367,2041.450686,1409.555689,1412.880825,1412.441122,Centro-Oeste,Mato Grosso do Sul
60,2976.847107,2110.500649,2233.300396,2214.904669,3294.468164,2581.450987,2493.169467,2504.77844,2361.409502,1606.346879,1840.774197,1799.507582,Centro-Oeste,Mato Grosso
62,2629.660891,1858.346611,2045.045929,2019.191162,3042.607139,2225.673004,2371.786029,2352.165729,2011.774112,1394.80011,1597.214843,1568.03137,Centro-Oeste,Goiás
64,5364.635021,2759.948258,3375.06529,3250.26101,6479.864521,3082.684223,3973.174141,3792.113828,2472.364584,2069.758008,2106.599992,2099.158699,Centro-Oeste,Distrito Federal

In [48]:
# Now I am separating into three section, because each section had a different type of job(Formal and Unofficial, Formal and Unofficial)
# So I created three Data Frame separating them
columns1 = ['Branca', 'Preta', 'Parda', 'Preta ou parda', 'Region', 'State']
columns2 = ['Branca.1', 'Preta.1', 'Parda.1', 'Preta ou parda.1', 'Region', 'State']
columns3 = ['Branca.2', 'Preta.2', 'Parda.2', 'Preta ou parda.2', 'Region', 'State']

df_Unofficial_Formal = df_cleaned[columns1].copy()
df_Formal = df_cleaned[columns2].copy()
df_Unofficial = df_cleaned[columns3].copy()

# Adding the column'Type' to specify which type the Data Frame is
df_Unofficial_Formal['Type'] = 'Formal and Unofficial'
df_Formal['Type'] = 'Formal'
df_Unofficial['Type'] = 'Unofficial'

In [49]:
# Now renaming and translating for better understanding for 3 Data Frame
df_Formal = df_Formal.rename(columns={'Branca.1': 'Branca', 'Preta.1': 'Preta', 'Parda.1': 'Parda', 'Preta ou parda.1': 'Preta ou parda'})
df_Unofficial = df_Unofficial.rename(columns={'Branca.2': 'Branca', 'Preta.2': 'Preta', 'Parda.2': 'Parda', 'Preta ou parda.2': 'Preta ou parda'})

new_column_names = {
    'Branca': 'White',
    'Preta': 'Black',
    'Parda': 'Mixed',
    'Preta ou parda': 'Black or Mixed',
}

df_Unofficial_Formal = df_Unofficial_Formal.rename(columns = new_column_names)
df_Formal = df_Formal.rename(columns = new_column_names)
df_Unofficial = df_Unofficial.rename(columns = new_column_names)

In [50]:
# Melting the DataFrames, by keeping the column 'Region', 'State' and 'Type' and transforming columns into row(with the column name 'Race')
# And the value name into 'Median_salary_per_month(R$)' 
df_Unofficial_Formal = df_Unofficial_Formal.melt(id_vars=['Region', 'State', 'Type'], 
                                                     value_vars=['White', 'Black', 'Mixed', 'Black or Mixed'],
                                                     var_name='Race', 
                                                     value_name='Median_salary_per_month(R$)')

df_Formal = df_Formal.melt(id_vars=['Region', 'State', 'Type'], 
                                 value_vars=['White', 'Black', 'Mixed', 'Black or Mixed'],
                                 var_name='Race', 
                                 value_name='Median_salary_per_month(R$)')

df_Unofficial = df_Unofficial.melt(id_vars=['Region', 'State', 'Type'], 
                                     value_vars=['White', 'Black', 'Mixed', 'Black or Mixed'],
                                     var_name='Race', 
                                     value_name='Median_salary_per_month(R$)')

# Concatenate all the melted DataFrames
df_result = pd.concat([df_Unofficial_Formal, df_Formal, df_Unofficial], ignore_index=True)
    
df_result['Year'] = 2021
df_result

,Region,State,Type,Race,Median_salary_per_month(R$),Year
0,Norte,Norte,Formal and Unofficial,White,2477.968905,2021
1,Norte,Rondônia,Formal and Unofficial,White,2209.917314,2021
2,Norte,Acre,Formal and Unofficial,White,2497.616416,2021
3,Norte,Amazonas,Formal and Unofficial,White,2501.462149,2021
4,Norte,Roraima,Formal and Unofficial,White,3560.763114,2021
...,...,...,...,...,...,...
403,Centro-Oeste,Centro-Oeste,Unofficial,Black or Mixed,1674.91996,2021
404,Centro-Oeste,Mato Grosso do Sul,Unofficial,Black or Mixed,1412.441122,2021
405,Centro-Oeste,Mato Grosso,Unofficial,Black or Mixed,1799.507582,2021
406,Centro-Oeste,Goiás,Unofficial,Black or Mixed,1568.03137,2021
407,Centro-Oeste,Distrito Federal,Unofficial,Black or Mixed,2099.158699,2021

In [51]:
# Is going to be the same cleaning process, however there is multiple years to automate
# The code above was to test and check if the Data Frame was clean and ready to use

import pandas as pd
import numpy as np

def process_salary_data(file_path, sheet_name):
    df_Financial = pd.read_excel(file_path, sheet_name=sheet_name)

    df_cleaned = df_Financial.copy()
    Rows_to_drop = [1, 2, 3, 66, 67, 68, 69, 70, 71, 72]
    df_cleaned = df_cleaned.drop(Rows_to_drop)
    df_cleaned = df_cleaned.dropna(how='all')

    rename_dict = {
        'Unnamed: 2': 'Branca',
        'Unnamed: 3': 'Preta',
        'Unnamed: 4': 'Parda',
        'Unnamed: 5': 'Preta ou parda',
        'Unnamed: 7': 'Branca.1',
        'Unnamed: 8': 'Preta.1',
        'Unnamed: 9': 'Parda.1',
        'Unnamed: 10': 'Preta ou parda.1',
        'Unnamed: 12': 'Branca.2',
        'Unnamed: 13': 'Preta.2',
        'Unnamed: 14': 'Parda.2',
        'Unnamed: 15': 'Preta ou parda.2'
    }

    df_cleaned = df_cleaned.rename(columns=rename_dict)
    df_cleaned.columns.values[0] = 'r'
    columns_to_drop = ['Unnamed: 1', 'Unnamed: 6', 'Unnamed: 11']
    df_cleaned = df_cleaned.drop(columns=columns_to_drop)
    Rows_to_drop = [4, 6]
    df_cleaned = df_cleaned.drop(Rows_to_drop)

    Region = {
        'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
        'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
        'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
        'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
        'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
    }

    df_cleaned.loc[:, 'Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)
    df_cleaned.loc[:, 'State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')

    region_to_drop = ['Brasil', 'Porto Velho', 'Rio Branco', 'Manaus', 'Boa Vista', 'Belém', 'Macapá', 'Palmas', 'São Luís', 'Teresina', 'Fortaleza', 'Natal', 'João Pessoa', 'Recife', 'Maceió', 'Aracaju', 'Salvador', 'Belo Horizonte', 'Vitória', 'Curitiba', 'Florianópolis', 'Porto Alegre', 'Campo Grande', 'Cuiabá', 'Goiânia', 'Brasília']
    df_cleaned = df_cleaned[~df_cleaned['Region'].isin(region_to_drop)]
    df_cleaned = df_cleaned.drop(columns='r')

    columns1 = ['Branca', 'Preta', 'Parda', 'Preta ou parda', 'Region', 'State']
    columns2 = ['Branca.1', 'Preta.1', 'Parda.1', 'Preta ou parda.1', 'Region', 'State']
    columns3 = ['Branca.2', 'Preta.2', 'Parda.2', 'Preta ou parda.2', 'Region', 'State']

    df_Unofficial_Formal = df_cleaned[columns1].copy()
    df_Formal = df_cleaned[columns2].copy()
    df_Unofficial = df_cleaned[columns3].copy()

    df_Unofficial_Formal['Type'] = 'Formal and Unofficial'
    df_Formal['Type'] = 'Formal'
    df_Unofficial['Type'] = 'Unofficial'

    df_Formal = df_Formal.rename(columns={'Branca.1': 'Branca', 'Preta.1': 'Preta', 'Parda.1': 'Parda', 'Preta ou parda.1': 'Preta ou parda'})
    df_Unofficial = df_Unofficial.rename(columns={'Branca.2': 'Branca', 'Preta.2': 'Preta', 'Parda.2': 'Parda', 'Preta ou parda.2': 'Preta ou parda'})

    new_column_names = {
        'Branca': 'White',
        'Preta': 'Black',
        'Parda': 'Mixed',
        'Preta ou parda': 'Black or Mixed',
    }

    df_Unofficial_Formal = df_Unofficial_Formal.rename(columns=new_column_names)
    df_Formal = df_Formal.rename(columns=new_column_names)
    df_Unofficial = df_Unofficial.rename(columns=new_column_names)

    df_Unofficial_Formal = df_Unofficial_Formal.melt(id_vars=['Region', 'State', 'Type'], 
                                                     value_vars=['White', 'Black', 'Mixed', 'Black or Mixed'],
                                                     var_name='Race', 
                                                     value_name='Median_salary_per_month(R$)')

    df_Formal = df_Formal.melt(id_vars=['Region', 'State', 'Type'], 
                                 value_vars=['White', 'Black', 'Mixed', 'Black or Mixed'],
                                 var_name='Race', 
                                 value_name='Median_salary_per_month(R$)')

    df_Unofficial = df_Unofficial.melt(id_vars=['Region', 'State', 'Type'], 
                                     value_vars=['White', 'Black', 'Mixed', 'Black or Mixed'],
                                     var_name='Race', 
                                     value_name='Median_salary_per_month(R$)')

    df_result = pd.concat([df_Unofficial_Formal, df_Formal, df_Unofficial], ignore_index=True)

    return df_result

def combine_salary_data(file_path, years):
    combined_df = pd.DataFrame()
    
    for year in years:
        sheet_name = str(year)
        df_year = process_salary_data(file_path, sheet_name)
        df_year['Year'] = year
        combined_df = pd.concat([combined_df, df_year], ignore_index=True)
    
    return combined_df

file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 2.5 (Rend_Form_Geo).xls'
years = [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012]

df_Finantial = combine_salary_data(file_path, years)
df_Finantial

,Region,State,Type,Race,Median_salary_per_month(R$),Year
0,Norte,Norte,Formal and Unofficial,White,2477.968905,2021
1,Norte,Rondônia,Formal and Unofficial,White,2209.917314,2021
2,Norte,Acre,Formal and Unofficial,White,2497.616416,2021
3,Norte,Amazonas,Formal and Unofficial,White,2501.462149,2021
4,Norte,Roraima,Formal and Unofficial,White,3560.763114,2021
...,...,...,...,...,...,...
4075,Centro-Oeste,Centro-Oeste,Unofficial,Black or Mixed,1601.396639,2012
4076,Centro-Oeste,Mato Grosso do Sul,Unofficial,Black or Mixed,1495.38241,2012
4077,Centro-Oeste,Mato Grosso,Unofficial,Black or Mixed,1485.720892,2012
4078,Centro-Oeste,Goiás,Unofficial,Black or Mixed,1558.85707,2012
4079,Centro-Oeste,Distrito Federal,Unofficial,Black or Mixed,2081.016883,2012

In [53]:
# Filtering Type for Formal
df_Salary_Race_Region_Formal = df_Finantial.copy()
df_Salary_Race_Region_Formal = df_Salary_Race_Region_Formal[df_Salary_Race_Region_Formal['Type'] == 'Formal']

# Filtering Race
race_in = ['White', 'Black', 'Mixed']
df_Salary_Race_Region_Formal = df_Salary_Race_Region_Formal[df_Salary_Race_Region_Formal['Race'].isin(race_in)]

# Keeping the necessary region and dropping the state column
State_to_keep = ['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste']
df_Salary_Race_Region_Formal = df_Salary_Race_Region_Formal[df_Salary_Race_Region_Formal['State'].isin(State_to_keep)]
df_Salary_Race_Region_Formal = df_Salary_Race_Region_Formal.drop(columns = 'State')

# Now I only want the year 2021
df_Salary_Race_Region_Formal_2021 = df_Salary_Race_Region_Formal[df_Salary_Race_Region_Formal['Year'] == 2021]

df_Salary_Race_Region_Formal_2021

           Region    Type   Race Median_salary_per_month(R$)  Year
136         Norte  Formal  White                 3339.416263  2021
144      Nordeste  Formal  White                 3158.723002  2021
154       Sudeste  Formal  White                 3801.789113  2021
161           Sul  Formal  White                 3073.833023  2021
165  Centro-Oeste  Formal  White                 4000.950471  2021
170         Norte  Formal  Black                 2309.993957  2021
178      Nordeste  Formal  Black                 1944.736298  2021
188       Sudeste  Formal  Black                 2250.763907  2021
195           Sul  Formal  Black                  2163.78776  2021
199  Centro-Oeste  Formal  Black                 2607.600578  2021
204         Norte  Formal  Mixed                 2372.072491  2021
212      Nordeste  Formal  Mixed                 2180.442943  2021
222       Sudeste  Formal  Mixed                 2357.757125  2021
229           Sul  Formal  Mixed                 2210.551105  2021
233  Centro-Oeste  Formal  Mixed                 2705.274811  2021

In [54]:
# Making a copy of the previous Data Frame
df_Salary_Race_Region_Formal_race = df_Salary_Race_Region_Formal.copy()
df_Salary_Race_Region_Formal_race = df_Salary_Race_Region_Formal_race.drop(columns = 'Region')

# Grouping by Year, Race and type and aggregating Salary to get the median of each year
df_Salary_Race_Region_Formal_race = df_Salary_Race_Region_Formal_race.groupby(['Year', 'Race', 'Type'])['Median_salary_per_month(R$)'].agg('median').reset_index()

# Sorting the values by year
df_Salary_Race_Region_Formal_race = df_Salary_Race_Region_Formal_race.sort_values(by = 'Year', ascending = False)
df_Salary_Race_Region_Formal_race

    Year   Race    Type Median_salary_per_month(R$)
29  2021  White  Formal                 3339.416263
28  2021  Mixed  Formal                 2357.757125
27  2021  Black  Formal                 2250.763907
26  2020  White  Formal                 3543.145244
25  2020  Mixed  Formal                 2406.475381
24  2020  Black  Formal                 2421.831658
23  2019  White  Formal                 3346.941381
22  2019  Mixed  Formal                  2375.37502
21  2019  Black  Formal                 2318.653106
20  2018  White  Formal                 3813.299837
19  2018  Mixed  Formal                 2425.810223
18  2018  Black  Formal                 2322.972005
16  2017  Mixed  Formal                 2349.117131
17  2017  White  Formal                 3699.534012
15  2017  Black  Formal                 2254.460078
14  2016  White  Formal                 3281.142162
13  2016  Mixed  Formal                 2291.239267
12  2016  Black  Formal                 2296.013991
11  2015  White  Formal                 3510.362664
10  2015  Mixed  Formal                 2304.444672
9   2015  Black  Formal                 2195.999097
8   2014  White  Formal                 3528.600966
7   2014  Mixed  Formal                 2331.722984
6   2014  Black  Formal                 2214.699613
5   2013  White  Formal                 3554.266589
4   2013  Mixed  Formal                 2255.990764
3   2013  Black  Formal                 2238.905856
1   2012  Mixed  Formal                 2228.860104
2   2012  White  Formal                 3620.063576
0   2012  Black  Formal                  2139.54413