In [30]:
# Importing the Data Frame from IBGE
import pandas as pd
import numpy as np


file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 3.1 (Pop_DomProp).xls'
df_Homelessness = pd.read_excel(file_path, sheet_name = '2019')
df_cleaned = df_Homelessness.copy()
df_cleaned

,"Tabela 3.1 - Total de pessoas e proporção da população residente em domicílios próprios, por cor ou raça, segundo as Grandes Regiões e as Unidades da Federação - Brasil - 2019",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Grandes Regiões e Unidades da Federação,Pessoas,NaN,NaN,NaN,NaN,NaN
3,NaN,Total\n(1 000 pessoas),Proporção da população residente em domicílios...,NaN,NaN,NaN,NaN
4,NaN,NaN,Total,Cor ou raça,NaN,NaN,NaN
5,NaN,NaN,NaN,Branca,Preta,Parda,Preta ou parda
6,Brasil,209496.463,72.307958,73.149049,71.098719,71.817012,71.696628
7,Norte,18113.187,77.509127,75.547061,73.879082,78.324243,77.917138
8,Rondônia,1766.689,70.921971,72.530049,67.880041,70.647883,70.37101
9,Acre,865.422,81.533403,80.512444,77.788957,82.166348,81.840154
10,Amazonas,3983.005,78.237095,75.250357,69.597377,78.860896,78.490613
11,Roraima,539.741,66.47356,60.685097,70.115768,67.349839,67.667868
12,Pará,8561.098,79.376098,77.022767,76.950629,80.178028,79.84506
13,Amapá,837.575,82.147811,82.039082,62.61357,84.128021,82.105214
14,Tocantins,1559.657,71.958578,72.875967,72.882661,71.798796,71.968071
15,Nordeste,56927.621,76.842772,76.22198,76.973707,77.085752,77.067762
16,Maranhão,7040.61,84.99502,83.651315,83.968449,85.481832,85.244654
17,Piauí,3272.447,85.403537,82.846448,85.070078,86.144958,86.006904
18,Ceará,9129.378,72.918733,75.972181,73.380506,71.64417,71.785379
19,Rio Grande do Norte,3506.853,73.672156,72.259695,76.431572,74.245482,74.534701
20,Paraíba,3996.784,72.300237,71.352039,70.649459,72.966681,72.727262
21,Pernambuco,9499.409,74.328028,73.957081,75.986741,74.179301,74.371996
22,Alagoas,3330.079,72.939106,74.084414,74.00598,72.547927,72.657961
23,Sergipe,2298.549,69.924982,71.536093,63.229019,70.323771,69.434358
24,Bahia,14853.512,79.029189,79.663094,76.72866,79.963693,79.04666
25,Sudeste,88350.161,69.161523,70.843675,68.315177,67.249646,67.46523
26,Minas Gerais,21158.152,72.443034,74.300768,71.315124,71.360076,71.351745
27,Espírito Santo,4014.926,68.978277,72.883161,66.31421,66.67446,66.61234
28,Rio de Janeiro,17264.41,73.5789,73.905309,73.425451,73.231347,73.281079
29,São Paulo,45912.673,66.00426,68.759748,63.105587,61.711084,61.977422
30,Sul,29932.24,74.058782,76.839,66.893495,66.711613,66.744095
31,Paraná,11420.565,71.024459,73.58225,63.371088,67.210919,66.774069
32,Santa Catarina,7153.029,73.501338,77.450498,57.734469,58.232588,58.154262
33,Rio Grande do Sul,11358.646,77.460692,79.061011,71.994154,71.708421,71.794821
34,Centro-Oeste,16173.254,64.468847,67.845055,62.307595,62.56237,62.524966
35,Mato Grosso do Sul,2709.334,63.466858,64.416446,59.162926,62.740978,62.358465
36,Mato Grosso,3430.698,66.010693,67.903601,66.42571,64.734693,65.014492
37,Goiás,7020.504,65.618437,70.276244,64.457368,62.97906,63.181536
38,Distrito Federal,3012.718,60.935299,66.113965,54.634805,58.306062,57.645662
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Dropping all the NaN row values
df_cleaned = df_cleaned.dropna(how = 'all')

# Setting the specified row to be the column
df_cleaned.columns = df_cleaned.iloc[3]

# Dropping the unnecessary rows such as description
rows_to_drop = [2, 3, 4, 5, 40]
df_cleaned = df_cleaned.drop(rows_to_drop)
df_cleaned

5,NaN,NaN,NaN,Branca,Preta,Parda,Preta ou parda
6,Brasil,209496.463,72.307958,73.149049,71.098719,71.817012,71.696628
7,Norte,18113.187,77.509127,75.547061,73.879082,78.324243,77.917138
8,Rondônia,1766.689,70.921971,72.530049,67.880041,70.647883,70.37101
9,Acre,865.422,81.533403,80.512444,77.788957,82.166348,81.840154
10,Amazonas,3983.005,78.237095,75.250357,69.597377,78.860896,78.490613
11,Roraima,539.741,66.47356,60.685097,70.115768,67.349839,67.667868
12,Pará,8561.098,79.376098,77.022767,76.950629,80.178028,79.84506
13,Amapá,837.575,82.147811,82.039082,62.61357,84.128021,82.105214
14,Tocantins,1559.657,71.958578,72.875967,72.882661,71.798796,71.968071
15,Nordeste,56927.621,76.842772,76.22198,76.973707,77.085752,77.067762
16,Maranhão,7040.61,84.99502,83.651315,83.968449,85.481832,85.244654
17,Piauí,3272.447,85.403537,82.846448,85.070078,86.144958,86.006904
18,Ceará,9129.378,72.918733,75.972181,73.380506,71.64417,71.785379
19,Rio Grande do Norte,3506.853,73.672156,72.259695,76.431572,74.245482,74.534701
20,Paraíba,3996.784,72.300237,71.352039,70.649459,72.966681,72.727262
21,Pernambuco,9499.409,74.328028,73.957081,75.986741,74.179301,74.371996
22,Alagoas,3330.079,72.939106,74.084414,74.00598,72.547927,72.657961
23,Sergipe,2298.549,69.924982,71.536093,63.229019,70.323771,69.434358
24,Bahia,14853.512,79.029189,79.663094,76.72866,79.963693,79.04666
25,Sudeste,88350.161,69.161523,70.843675,68.315177,67.249646,67.46523
26,Minas Gerais,21158.152,72.443034,74.300768,71.315124,71.360076,71.351745
27,Espírito Santo,4014.926,68.978277,72.883161,66.31421,66.67446,66.61234
28,Rio de Janeiro,17264.41,73.5789,73.905309,73.425451,73.231347,73.281079
29,São Paulo,45912.673,66.00426,68.759748,63.105587,61.711084,61.977422
30,Sul,29932.24,74.058782,76.839,66.893495,66.711613,66.744095
31,Paraná,11420.565,71.024459,73.58225,63.371088,67.210919,66.774069
32,Santa Catarina,7153.029,73.501338,77.450498,57.734469,58.232588,58.154262
33,Rio Grande do Sul,11358.646,77.460692,79.061011,71.994154,71.708421,71.794821
34,Centro-Oeste,16173.254,64.468847,67.845055,62.307595,62.56237,62.524966
35,Mato Grosso do Sul,2709.334,63.466858,64.416446,59.162926,62.740978,62.358465
36,Mato Grosso,3430.698,66.010693,67.903601,66.42571,64.734693,65.014492
37,Goiás,7020.504,65.618437,70.276244,64.457368,62.97906,63.181536
38,Distrito Federal,3012.718,60.935299,66.113965,54.634805,58.306062,57.645662

In [32]:
# Changing first three column names
df_cleaned.columns.values[0] = 'r'
df_cleaned.columns.values[1] = 'Quantity(10^3)'
df_cleaned.columns.values[2] = 'Total'

# Translating to english for better understanding
new_column_names = {
    'Branca': 'White',
    'Preta': 'Black',
    'Parda': 'Mixed',
    'Preta ou parda': 'Black or Mixed',
    'Quantity': 'Quantity(10^3)'
}

df_cleaned = df_cleaned.rename(columns = new_column_names)
df_cleaned

5,r,Quantity(10^3),Total,White,Black,Mixed,Black or Mixed
6,Brasil,209496.463,72.307958,73.149049,71.098719,71.817012,71.696628
7,Norte,18113.187,77.509127,75.547061,73.879082,78.324243,77.917138
8,Rondônia,1766.689,70.921971,72.530049,67.880041,70.647883,70.37101
9,Acre,865.422,81.533403,80.512444,77.788957,82.166348,81.840154
10,Amazonas,3983.005,78.237095,75.250357,69.597377,78.860896,78.490613
11,Roraima,539.741,66.47356,60.685097,70.115768,67.349839,67.667868
12,Pará,8561.098,79.376098,77.022767,76.950629,80.178028,79.84506
13,Amapá,837.575,82.147811,82.039082,62.61357,84.128021,82.105214
14,Tocantins,1559.657,71.958578,72.875967,72.882661,71.798796,71.968071
15,Nordeste,56927.621,76.842772,76.22198,76.973707,77.085752,77.067762
16,Maranhão,7040.61,84.99502,83.651315,83.968449,85.481832,85.244654
17,Piauí,3272.447,85.403537,82.846448,85.070078,86.144958,86.006904
18,Ceará,9129.378,72.918733,75.972181,73.380506,71.64417,71.785379
19,Rio Grande do Norte,3506.853,73.672156,72.259695,76.431572,74.245482,74.534701
20,Paraíba,3996.784,72.300237,71.352039,70.649459,72.966681,72.727262
21,Pernambuco,9499.409,74.328028,73.957081,75.986741,74.179301,74.371996
22,Alagoas,3330.079,72.939106,74.084414,74.00598,72.547927,72.657961
23,Sergipe,2298.549,69.924982,71.536093,63.229019,70.323771,69.434358
24,Bahia,14853.512,79.029189,79.663094,76.72866,79.963693,79.04666
25,Sudeste,88350.161,69.161523,70.843675,68.315177,67.249646,67.46523
26,Minas Gerais,21158.152,72.443034,74.300768,71.315124,71.360076,71.351745
27,Espírito Santo,4014.926,68.978277,72.883161,66.31421,66.67446,66.61234
28,Rio de Janeiro,17264.41,73.5789,73.905309,73.425451,73.231347,73.281079
29,São Paulo,45912.673,66.00426,68.759748,63.105587,61.711084,61.977422
30,Sul,29932.24,74.058782,76.839,66.893495,66.711613,66.744095
31,Paraná,11420.565,71.024459,73.58225,63.371088,67.210919,66.774069
32,Santa Catarina,7153.029,73.501338,77.450498,57.734469,58.232588,58.154262
33,Rio Grande do Sul,11358.646,77.460692,79.061011,71.994154,71.708421,71.794821
34,Centro-Oeste,16173.254,64.468847,67.845055,62.307595,62.56237,62.524966
35,Mato Grosso do Sul,2709.334,63.466858,64.416446,59.162926,62.740978,62.358465
36,Mato Grosso,3430.698,66.010693,67.903601,66.42571,64.734693,65.014492
37,Goiás,7020.504,65.618437,70.276244,64.457368,62.97906,63.181536
38,Distrito Federal,3012.718,60.935299,66.113965,54.634805,58.306062,57.645662

In [33]:
# Create a dictionary mapping Brazilian states and regions to their respective regions
Region = {
    'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
    'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
    'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
    'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
    'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
}

# Create a new column 'Region' in the DataFrame 'df_cleaned'
# Use the 'apply' function to map the state names in column 'r'(region) to their respective regions based on the 'Region' dictionary
# If the state name is in the 'Region' dictionary, assign the corresponding region; otherwise, keep the state name as is
df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)

# Create a new column 'State' in the DataFrame 'df_cleaned'
# Use the 'apply' function to check if the state name in column 'r' is present in the 'Region' dictionary
# If the state name is in the dictionary, keep it; otherwise, assign an empty string
df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')

# Drop the original column 'r' from the DataFrame 'df_cleaned' as it is no longer needed
df_cleaned = df_cleaned.drop(columns = 'r')

df_cleaned

5,Quantity(10^3),Total,White,Black,Mixed,Black or Mixed,Region,State
6,209496.463,72.307958,73.149049,71.098719,71.817012,71.696628,Brasil,
7,18113.187,77.509127,75.547061,73.879082,78.324243,77.917138,Norte,Norte
8,1766.689,70.921971,72.530049,67.880041,70.647883,70.37101,Norte,Rondônia
9,865.422,81.533403,80.512444,77.788957,82.166348,81.840154,Norte,Acre
10,3983.005,78.237095,75.250357,69.597377,78.860896,78.490613,Norte,Amazonas
11,539.741,66.47356,60.685097,70.115768,67.349839,67.667868,Norte,Roraima
12,8561.098,79.376098,77.022767,76.950629,80.178028,79.84506,Norte,Pará
13,837.575,82.147811,82.039082,62.61357,84.128021,82.105214,Norte,Amapá
14,1559.657,71.958578,72.875967,72.882661,71.798796,71.968071,Norte,Tocantins
15,56927.621,76.842772,76.22198,76.973707,77.085752,77.067762,Nordeste,Nordeste
16,7040.61,84.99502,83.651315,83.968449,85.481832,85.244654,Nordeste,Maranhão
17,3272.447,85.403537,82.846448,85.070078,86.144958,86.006904,Nordeste,Piauí
18,9129.378,72.918733,75.972181,73.380506,71.64417,71.785379,Nordeste,Ceará
19,3506.853,73.672156,72.259695,76.431572,74.245482,74.534701,Nordeste,Rio Grande do Norte
20,3996.784,72.300237,71.352039,70.649459,72.966681,72.727262,Nordeste,Paraíba
21,9499.409,74.328028,73.957081,75.986741,74.179301,74.371996,Nordeste,Pernambuco
22,3330.079,72.939106,74.084414,74.00598,72.547927,72.657961,Nordeste,Alagoas
23,2298.549,69.924982,71.536093,63.229019,70.323771,69.434358,Nordeste,Sergipe
24,14853.512,79.029189,79.663094,76.72866,79.963693,79.04666,Nordeste,Bahia
25,88350.161,69.161523,70.843675,68.315177,67.249646,67.46523,Sudeste,Sudeste
26,21158.152,72.443034,74.300768,71.315124,71.360076,71.351745,Sudeste,Minas Gerais
27,4014.926,68.978277,72.883161,66.31421,66.67446,66.61234,Sudeste,Espírito Santo
28,17264.41,73.5789,73.905309,73.425451,73.231347,73.281079,Sudeste,Rio de Janeiro
29,45912.673,66.00426,68.759748,63.105587,61.711084,61.977422,Sudeste,São Paulo
30,29932.24,74.058782,76.839,66.893495,66.711613,66.744095,Sul,Sul
31,11420.565,71.024459,73.58225,63.371088,67.210919,66.774069,Sul,Paraná
32,7153.029,73.501338,77.450498,57.734469,58.232588,58.154262,Sul,Santa Catarina
33,11358.646,77.460692,79.061011,71.994154,71.708421,71.794821,Sul,Rio Grande do Sul
34,16173.254,64.468847,67.845055,62.307595,62.56237,62.524966,Centro-Oeste,Centro-Oeste
35,2709.334,63.466858,64.416446,59.162926,62.740978,62.358465,Centro-Oeste,Mato Grosso do Sul
36,3430.698,66.010693,67.903601,66.42571,64.734693,65.014492,Centro-Oeste,Mato Grosso
37,7020.504,65.618437,70.276244,64.457368,62.97906,63.181536,Centro-Oeste,Goiás
38,3012.718,60.935299,66.113965,54.634805,58.306062,57.645662,Centro-Oeste,Distrito Federal

In [34]:
# Melting the Data Frame to transform the columns into rows(Race), and keeping the Region, State, and Quantity(10^3)

df_cleaned = df_cleaned.melt(id_vars=['Region', 'State', 'Quantity(10^3)'], 
                value_vars = ['White', 'Black', 'Mixed', 'Black or Mixed'],
                var_name = 'Race',  
                value_name ='Proportion_of_not_homeless')

df_cleaned

,Region,State,Quantity(10^3),Race,Proportion_of_not_homeless
0,Brasil,,209496.463,White,73.149049
1,Norte,Norte,18113.187,White,75.547061
2,Norte,Rondônia,1766.689,White,72.530049
3,Norte,Acre,865.422,White,80.512444
4,Norte,Amazonas,3983.005,White,75.250357
...,...,...,...,...,...
127,Centro-Oeste,Centro-Oeste,16173.254,Black or Mixed,62.524966
128,Centro-Oeste,Mato Grosso do Sul,2709.334,Black or Mixed,62.358465
129,Centro-Oeste,Mato Grosso,3430.698,Black or Mixed,65.014492
130,Centro-Oeste,Goiás,7020.504,Black or Mixed,63.181536
131,Centro-Oeste,Distrito Federal,3012.718,Black or Mixed,57.645662

In [35]:
# I wanted to insert a new column containing the Proportion of homeless people
df_cleaned = df_cleaned.drop(columns = 'Quantity(10^3)')
df_cleaned['Proportion_of_homeless'] = 100 - df_cleaned['Proportion_of_not_homeless']

# Adding the column Year to specify which year it is and dropping the total proportion (Brazil)
df_cleaned = df_cleaned.drop(0)
df_cleaned['Year'] = 2019
df_cleaned

,Region,State,Race,Proportion_of_not_homeless,Proportion_of_homeless,Year
1,Norte,Norte,White,75.547061,24.452939,2019
2,Norte,Rondônia,White,72.530049,27.469951,2019
3,Norte,Acre,White,80.512444,19.487556,2019
4,Norte,Amazonas,White,75.250357,24.749643,2019
5,Norte,Roraima,White,60.685097,39.314903,2019
...,...,...,...,...,...,...
127,Centro-Oeste,Centro-Oeste,Black or Mixed,62.524966,37.475034,2019
128,Centro-Oeste,Mato Grosso do Sul,Black or Mixed,62.358465,37.641535,2019
129,Centro-Oeste,Mato Grosso,Black or Mixed,65.014492,34.985508,2019
130,Centro-Oeste,Goiás,Black or Mixed,63.181536,36.818464,2019
131,Centro-Oeste,Distrito Federal,Black or Mixed,57.645662,42.354338,2019

In [14]:
# Is going to be the same cleaning process, however there is multiple years to automate
# The code above was to test and check if the Data Frame was clean and ready to use

def process_population_data_homeless(file_path, sheet_name):

    df_Homelessness = pd.read_excel(file_path, sheet_name = sheet_name)


    df_cleaned = df_Homelessness.copy()
    df_cleaned = df_cleaned.dropna(how = 'all')
    df_cleaned.columns = df_cleaned.iloc[3]

    rows_to_drop = [2, 3, 4, 5, 40]
    df_cleaned = df_cleaned.drop(rows_to_drop)
    df_cleaned.columns.values[0] = 'r'
    df_cleaned.columns.values[1] = 'Quantity(10^3)'
    df_cleaned.columns.values[2] = 'Total'


    new_column_names = {
        'Branca': 'White',
        'Preta': 'Black',
        'Parda': 'Mixed',
        'Preta ou parda': 'Black or Mixed',
        'Quantity': 'Quantity(10^3)'
    }

    df_cleaned = df_cleaned.rename(columns = new_column_names)

    Region = {
    'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
    'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
    'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
    'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
    'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
    }


    df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)
    df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')
    df_cleaned = df_cleaned.drop(columns = 'r')
    

    df_cleaned = df_cleaned.melt(id_vars=['Region', 'State', 'Quantity(10^3)'], 
                    value_vars = ['White', 'Black', 'Mixed', 'Black or Mixed'],
                    var_name = 'Race',  
                    value_name ='Proportion_of_not_homeless')
    
    return df_cleaned

def combine_data(file_path, years):
    combined_df = pd.DataFrame()

    for year in years:
        sheet_name = str(year)
        df_year = process_population_data_homeless(file_path, sheet_name)
        df_year['Year'] = year
        combined_df = pd.concat([combined_df, df_year], ignore_index = True)
    
    return combined_df

file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 3.1 (Pop_DomProp).xls'
years = [2019, 2018, 2017, 2016] 

df_Homelessness = combine_data(file_path, years)
df_Homelessness = df_Homelessness.drop(columns = 'Quantity(10^3)')
df_Homelessness['Proportion_of_homeless'] = 100 - df_Homelessness['Proportion_of_not_homeless']
df_Homelessness = df_Homelessness.drop(0)
df_Homelessness

,Region,State,Race,Proportion_of_not_homeless,Year,Proportion_of_homeless
1,Norte,Norte,White,75.547061,2019,24.452939
2,Norte,Rondônia,White,72.530049,2019,27.469951
3,Norte,Acre,White,80.512444,2019,19.487556
4,Norte,Amazonas,White,75.250357,2019,24.749643
5,Norte,Roraima,White,60.685097,2019,39.314903
...,...,...,...,...,...,...
523,Centro-Oeste,Centro-Oeste,Black or Mixed,64.914096,2016,35.085904
524,Centro-Oeste,Mato Grosso do Sul,Black or Mixed,65.646972,2016,34.353028
525,Centro-Oeste,Mato Grosso,Black or Mixed,66.852785,2016,33.147215
526,Centro-Oeste,Goiás,Black or Mixed,66.840117,2016,33.159883
527,Centro-Oeste,Distrito Federal,Black or Mixed,57.214614,2016,42.785386

In [23]:
# In this analysis I only want the Region and in the year 2019
df_Homelessness_only_region = df_Homelessness.copy()

# Filtering for year 2019
df_Homelessness_only_region = df_Homelessness_only_region[df_Homelessness_only_region['Year'] == 2019]

# Keeping the races that I need
row_to_keep = ['White', 'Black', 'Mixed']
df_Homelessness_only_region = df_Homelessness_only_region[df_Homelessness_only_region['Race'].isin(row_to_keep)]

# Grouping by region, race and year, then calculating the median of homeless people in each region by race
df_Homelessness_only_region = df_Homelessness_only_region.groupby(['Region', 'Race', 'Year'])['Proportion_of_homeless'].agg('median').reset_index()

# Dropping the rows that contains total proportion
df_Homelessness_only_region = df_Homelessness_only_region.drop([0, 1])
df_Homelessness_only_region

          Region   Race  Year Proportion_of_homeless
2   Centro-Oeste  Black  2019              37.692405
3   Centro-Oeste  Mixed  2019              37.259022
4   Centro-Oeste  White  2019              32.154945
5       Nordeste  Black  2019              23.790844
6       Nordeste  Mixed  2019              25.787608
7       Nordeste  White  2019              24.971702
8          Norte  Black  2019              28.500786
9          Norte  Mixed  2019               21.40743
10         Norte  White  2019              24.601291
11       Sudeste  Black  2019              31.684823
12       Sudeste  Mixed  2019              32.750354
13       Sudeste  White  2019              27.116839
14           Sul  Black  2019              34.867709
15           Sul  Mixed  2019              33.038734
16           Sul  White  2019              22.855251

In [15]:
# In this analysis I want to display the Proportion of homeless people by race
df_Homelessness_only_race = df_Homelessness.copy()

# Dropping the columns that I dont need
columns_to_drop = ['Region', 'Proportion_of_not_homeless']
df_Homelessness_only_race = df_Homelessness_only_race.drop(columns = columns_to_drop)

# Grouping by Race and Year, and calculating the median of homeless people
df_Homelessness_only_race = df_Homelessness_only_race.groupby(['Race', 'Year'])['Proportion_of_homeless'].agg('median').reset_index()
df_Homelessness_only_race = df_Homelessness_only_race.sort_values(by = 'Year', ascending = False)

df_Homelessness_only_race

              Race  Year Proportion_of_homeless
3            Black  2019              29.350541
7   Black or Mixed  2019              28.214621
11           Mixed  2019              28.291579
15           White  2019              26.068805
2            Black  2018              30.134002
6   Black or Mixed  2018              28.536322
10           Mixed  2018              28.131535
14           White  2018               25.69991
1            Black  2017              29.179845
5   Black or Mixed  2017              26.759237
9            Mixed  2017              26.990207
13           White  2017              24.036821
0            Black  2016              27.172954
4   Black or Mixed  2016              26.761596
8            Mixed  2016               26.59127
12           White  2016              24.530482