In [23]:
# Importing the Data Frame from IBGE

import pandas as pd
import numpy as np

file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 6.1 (Pref_Veread_Eleit_Geo).xls'
df_Politics = pd.read_excel(file_path, sheet_name = '2020')
df_cleaned = df_Politics.copy()
df_cleaned

,"Tabela 6.1 - Prefeitos e vereadores eleitos, por cor ou raça, segundo características selecionadas dos eleitos, classes de tamanho dos municípios, Grandes Regiões e Unidades da Federação - 2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Características selecionadas dos eleitos, clas...",Eleitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Prefeitos,NaN,NaN,NaN,NaN,NaN,Vereadores,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,Cor ou raça (1),NaN,NaN,NaN,NaN,Total,Cor ou raça (1),NaN,NaN,NaN,NaN
4,NaN,NaN,Branca,Preta,Parda,Amarela,Indígena,NaN,Branca,Preta,Parda,Amarela,Indígena
5,Brasil,5502,3691,111,1650,23,8,58090,31109,3591,22393,232,184
6,Homens,4839,3248,101,1449,16,7,48789,25621,3100,19233,185,155
7,Mulheres,663,443,10,201,7,1,9301,5488,491,3160,47,29
8,Classes de tamanho dos municípios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Até 5 000 hab.,1240,892,19,315,7,0,11232,7075,516,3443,48,24
10,De 5 001 a 10 000 hab.,1180,794,26,351,5,1,10802,5864,605,4167,45,35
11,De 10 001 a 20 000 hab.,1317,852,30,419,6,6,12735,6301,747,5487,49,52
12,De 20 001 a 50 000 hab.,1096,674,23,389,5,1,12519,5932,869,5433,42,56
13,De 50 001 a 100 000 hab.,346,235,9,102,0,0,4830,2527,318,1932,14,9
14,De 100 001 a 500 000 hab.,275,205,4,65,0,0,4625,2640,393,1525,17,6
15,Mais de 500 000 hab.,48,39,0,9,0,0,1347,770,143,406,17,2
16,Grandes Regiões e Unidades da Federação,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Norte,447,157,16,263,3,4,4889,1088,386,3257,25,70
18,Rondônia,52,29,0,23,0,0,533,205,47,269,5,4
19,Acre,22,4,1,16,0,1,231,37,14,169,4,7
20,Amazonas,61,13,0,47,0,1,723,137,24,522,1,35
21,Roraima,15,4,1,8,0,2,157,21,5,121,0,10
22,Pará,142,41,5,94,1,0,1764,387,143,1200,6,7
23,Amapá,16,6,1,8,0,0,174,31,17,122,0,2
24,Tocantins,139,60,8,67,2,0,1307,270,136,854,9,5
25,Nordeste,1777,812,59,887,8,2,19294,6221,1470,11205,100,55
26,Maranhão,217,92,9,115,0,0,2425,669,194,1507,12,8
27,Piauí,222,88,7,123,2,0,2144,581,147,1367,16,1
28,Ceará,179,89,0,88,1,0,2192,822,74,1269,6,3
29,Rio Grande do Norte,166,109,3,53,1,0,1654,823,72,742,7,0
30,Paraíba,221,112,5,102,1,1,2207,860,104,1183,15,16
31,Pernambuco,180,100,9,70,0,0,2151,867,138,1113,4,13
32,Alagoas,101,52,1,46,1,1,1086,421,34,614,4,4
33,Sergipe,75,26,1,46,0,0,805,160,76,550,5,1
34,Bahia,416,144,24,244,2,0,4630,1018,631,2860,31,9
35,Sudeste,1633,1302,28,294,4,1,17487,11289,1144,4781,65,12
36,Minas Gerais,844,586,21,231,3,1,8480,4623,635,3084,32,7
37,Espírito Santo,77,57,0,19,1,0,860,479,66,288,3,1
38,Rio de Janeiro,88,76,1,11,0,0,1184,781,77,288,3,0
39,São Paulo,624,583,6,33,0,0,6963,5406,366,1121,27,4
40,Sul,1185,1135,1,45,2,1,11653,10360,288,932,13,22
41,Paraná,396,365,1,29,1,0,3869,3101,140,596,9,4
42,Santa Catarina,294,285,0,8,1,0,2890,2685,41,150,2,4
43,Rio Grande do Sul,495,485,0,8,0,1,4894,4574,107,186,2,14
44,Centro-Oeste,460,285,7,161,6,0,4767,2151,303,2218,29,25
45,Mato Grosso do Sul,75,62,1,10,2,0,847,499,47,268,5,13
46,Mato Grosso,139,90,1,47,1,0,1404,578,104,696,9,11
47,Goiás,246,133,5,104,3,0,2516,1074,152,1254,15,1
48,Distrito Federal,..,..,..,..,..,..,..,..,..,..,..,..
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Fonte: Portal de dados abertos do TSE. Disponí...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Notas: Os resultados apresentados se referem a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,(1) Não inclui candidatos cujas informações co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Dropping the unnecessary rows such as description
rows_to_drop = [0, 1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 49, 50, 51, 52]
df_cleaned = df_cleaned.drop(rows_to_drop)

# Replacing the rows value name for better organization
replacement_dict = {
    'Branca': 'Branca.1',
    'Preta': 'Preta.1',
    'Parda': 'Parda.1',
    'Amarela': 'Amarela.1',
    'Indígena': 'Indígena.1'
}

# Apply the replacement dictionary to all specified columns
columns_to_replace = ['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
df_cleaned[columns_to_replace] = df_cleaned[columns_to_replace].replace(replacement_dict)

df_cleaned

,"Tabela 6.1 - Prefeitos e vereadores eleitos, por cor ou raça, segundo características selecionadas dos eleitos, classes de tamanho dos municípios, Grandes Regiões e Unidades da Federação - 2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
4,NaN,NaN,Branca,Preta,Parda,Amarela,Indígena,NaN,Branca.1,Preta.1,Parda.1,Amarela.1,Indígena.1
5,Brasil,5502,3691,111,1650,23,8,58090,31109,3591,22393,232,184
17,Norte,447,157,16,263,3,4,4889,1088,386,3257,25,70
18,Rondônia,52,29,0,23,0,0,533,205,47,269,5,4
19,Acre,22,4,1,16,0,1,231,37,14,169,4,7
20,Amazonas,61,13,0,47,0,1,723,137,24,522,1,35
21,Roraima,15,4,1,8,0,2,157,21,5,121,0,10
22,Pará,142,41,5,94,1,0,1764,387,143,1200,6,7
23,Amapá,16,6,1,8,0,0,174,31,17,122,0,2
24,Tocantins,139,60,8,67,2,0,1307,270,136,854,9,5
25,Nordeste,1777,812,59,887,8,2,19294,6221,1470,11205,100,55
26,Maranhão,217,92,9,115,0,0,2425,669,194,1507,12,8
27,Piauí,222,88,7,123,2,0,2144,581,147,1367,16,1
28,Ceará,179,89,0,88,1,0,2192,822,74,1269,6,3
29,Rio Grande do Norte,166,109,3,53,1,0,1654,823,72,742,7,0
30,Paraíba,221,112,5,102,1,1,2207,860,104,1183,15,16
31,Pernambuco,180,100,9,70,0,0,2151,867,138,1113,4,13
32,Alagoas,101,52,1,46,1,1,1086,421,34,614,4,4
33,Sergipe,75,26,1,46,0,0,805,160,76,550,5,1
34,Bahia,416,144,24,244,2,0,4630,1018,631,2860,31,9
35,Sudeste,1633,1302,28,294,4,1,17487,11289,1144,4781,65,12
36,Minas Gerais,844,586,21,231,3,1,8480,4623,635,3084,32,7
37,Espírito Santo,77,57,0,19,1,0,860,479,66,288,3,1
38,Rio de Janeiro,88,76,1,11,0,0,1184,781,77,288,3,0
39,São Paulo,624,583,6,33,0,0,6963,5406,366,1121,27,4
40,Sul,1185,1135,1,45,2,1,11653,10360,288,932,13,22
41,Paraná,396,365,1,29,1,0,3869,3101,140,596,9,4
42,Santa Catarina,294,285,0,8,1,0,2890,2685,41,150,2,4
43,Rio Grande do Sul,495,485,0,8,0,1,4894,4574,107,186,2,14
44,Centro-Oeste,460,285,7,161,6,0,4767,2151,303,2218,29,25
45,Mato Grosso do Sul,75,62,1,10,2,0,847,499,47,268,5,13
46,Mato Grosso,139,90,1,47,1,0,1404,578,104,696,9,11
47,Goiás,246,133,5,104,3,0,2516,1074,152,1254,15,1
48,Distrito Federal,..,..,..,..,..,..,..,..,..,..,..,..

In [25]:
# Setting the columns name with the values of the first row
df_cleaned.columns = df_cleaned.iloc[0]

# Now dropping that row because is not wanted anymore, also the fifth row which is not wanted in my analysis
rows_to_drop = [4, 5]
df_cleaned = df_cleaned.drop(rows_to_drop)

# Renaming the first column to r (region)
df_cleaned.columns.values[0] = 'r'

# Dropping the NaN columns, they are the total which is not necessary for my analysis
columns_to_drop = [col for col in df_cleaned.columns if pd.isna(col)]
df_cleaned = df_cleaned.drop(columns = columns_to_drop)
df_cleaned

4,r,Branca,Preta,Parda,Amarela,Indígena,Branca.1,Preta.1,Parda.1,Amarela.1,Indígena.1
17,Norte,157,16,263,3,4,1088,386,3257,25,70
18,Rondônia,29,0,23,0,0,205,47,269,5,4
19,Acre,4,1,16,0,1,37,14,169,4,7
20,Amazonas,13,0,47,0,1,137,24,522,1,35
21,Roraima,4,1,8,0,2,21,5,121,0,10
22,Pará,41,5,94,1,0,387,143,1200,6,7
23,Amapá,6,1,8,0,0,31,17,122,0,2
24,Tocantins,60,8,67,2,0,270,136,854,9,5
25,Nordeste,812,59,887,8,2,6221,1470,11205,100,55
26,Maranhão,92,9,115,0,0,669,194,1507,12,8
27,Piauí,88,7,123,2,0,581,147,1367,16,1
28,Ceará,89,0,88,1,0,822,74,1269,6,3
29,Rio Grande do Norte,109,3,53,1,0,823,72,742,7,0
30,Paraíba,112,5,102,1,1,860,104,1183,15,16
31,Pernambuco,100,9,70,0,0,867,138,1113,4,13
32,Alagoas,52,1,46,1,1,421,34,614,4,4
33,Sergipe,26,1,46,0,0,160,76,550,5,1
34,Bahia,144,24,244,2,0,1018,631,2860,31,9
35,Sudeste,1302,28,294,4,1,11289,1144,4781,65,12
36,Minas Gerais,586,21,231,3,1,4623,635,3084,32,7
37,Espírito Santo,57,0,19,1,0,479,66,288,3,1
38,Rio de Janeiro,76,1,11,0,0,781,77,288,3,0
39,São Paulo,583,6,33,0,0,5406,366,1121,27,4
40,Sul,1135,1,45,2,1,10360,288,932,13,22
41,Paraná,365,1,29,1,0,3101,140,596,9,4
42,Santa Catarina,285,0,8,1,0,2685,41,150,2,4
43,Rio Grande do Sul,485,0,8,0,1,4574,107,186,2,14
44,Centro-Oeste,285,7,161,6,0,2151,303,2218,29,25
45,Mato Grosso do Sul,62,1,10,2,0,499,47,268,5,13
46,Mato Grosso,90,1,47,1,0,578,104,696,9,11
47,Goiás,133,5,104,3,0,1074,152,1254,15,1
48,Distrito Federal,..,..,..,..,..,..,..,..,..,..

In [26]:
# Create a dictionary mapping Brazilian states and regions to their respective regions
Region = {
    'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
    'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
    'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
    'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
    'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
}

# Create a new column 'Region' in the DataFrame 'df_cleaned'
# Use the 'apply' function to map the state names in column 'r'(region) to their respective regions based on the 'Region' dictionary
# If the state name is in the 'Region' dictionary, assign the corresponding region; otherwise, keep the state name as is
df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)

# Create a new column 'State' in the DataFrame 'df_cleaned'
# Use the 'apply' function to check if the state name in column 'r' is present in the 'Region' dictionary
# If the state name is in the dictionary, keep it; otherwise, assign an empty string
df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')

# Drop the original column 'r' from the DataFrame 'df_cleaned' as it is no longer needed
df_cleaned = df_cleaned.drop(columns = 'r')

df_cleaned

4,Branca,Preta,Parda,Amarela,Indígena,Branca.1,Preta.1,Parda.1,Amarela.1,Indígena.1,Region,State
17,157,16,263,3,4,1088,386,3257,25,70,Norte,Norte
18,29,0,23,0,0,205,47,269,5,4,Norte,Rondônia
19,4,1,16,0,1,37,14,169,4,7,Norte,Acre
20,13,0,47,0,1,137,24,522,1,35,Norte,Amazonas
21,4,1,8,0,2,21,5,121,0,10,Norte,Roraima
22,41,5,94,1,0,387,143,1200,6,7,Norte,Pará
23,6,1,8,0,0,31,17,122,0,2,Norte,Amapá
24,60,8,67,2,0,270,136,854,9,5,Norte,Tocantins
25,812,59,887,8,2,6221,1470,11205,100,55,Nordeste,Nordeste
26,92,9,115,0,0,669,194,1507,12,8,Nordeste,Maranhão
27,88,7,123,2,0,581,147,1367,16,1,Nordeste,Piauí
28,89,0,88,1,0,822,74,1269,6,3,Nordeste,Ceará
29,109,3,53,1,0,823,72,742,7,0,Nordeste,Rio Grande do Norte
30,112,5,102,1,1,860,104,1183,15,16,Nordeste,Paraíba
31,100,9,70,0,0,867,138,1113,4,13,Nordeste,Pernambuco
32,52,1,46,1,1,421,34,614,4,4,Nordeste,Alagoas
33,26,1,46,0,0,160,76,550,5,1,Nordeste,Sergipe
34,144,24,244,2,0,1018,631,2860,31,9,Nordeste,Bahia
35,1302,28,294,4,1,11289,1144,4781,65,12,Sudeste,Sudeste
36,586,21,231,3,1,4623,635,3084,32,7,Sudeste,Minas Gerais
37,57,0,19,1,0,479,66,288,3,1,Sudeste,Espírito Santo
38,76,1,11,0,0,781,77,288,3,0,Sudeste,Rio de Janeiro
39,583,6,33,0,0,5406,366,1121,27,4,Sudeste,São Paulo
40,1135,1,45,2,1,10360,288,932,13,22,Sul,Sul
41,365,1,29,1,0,3101,140,596,9,4,Sul,Paraná
42,285,0,8,1,0,2685,41,150,2,4,Sul,Santa Catarina
43,485,0,8,0,1,4574,107,186,2,14,Sul,Rio Grande do Sul
44,285,7,161,6,0,2151,303,2218,29,25,Centro-Oeste,Centro-Oeste
45,62,1,10,2,0,499,47,268,5,13,Centro-Oeste,Mato Grosso do Sul
46,90,1,47,1,0,578,104,696,9,11,Centro-Oeste,Mato Grosso
47,133,5,104,3,0,1074,152,1254,15,1,Centro-Oeste,Goiás
48,..,..,..,..,..,..,..,..,..,..,Centro-Oeste,Distrito Federal

In [28]:
# Now separating into two section Mayor and City Councilor, this is what IBGE provided
columns1 = ['Branca', 'Preta', 'Parda', 'Amarela', 'Indígena', 'Region', 'State']
columns2 = ['Branca.1', 'Preta.1', 'Parda.1', 'Amarela.1', 'Indígena.1', 'Region', 'State']

df_cleaned_Mayor = df_cleaned[columns1].copy()
df_cleaned_City = df_cleaned[columns2].copy()

# Specifying the position 
df_cleaned_Mayor['Position'] = 'Mayor'
df_cleaned_City['Position'] = 'City ​​Councilor'

In [29]:
# translating to english for better understanding
new_column_names_1 = {
        'Branca': 'White',
        'Preta': 'Black',
        'Parda': 'Mixed',
        'Amarela': 'East Asian',
        'Indígena': 'Native'
}

new_column_names_2 = {
        'Branca.1': 'White',
        'Preta.1': 'Black',
        'Parda.1': 'Mixed',
        'Amarela.1': 'East Asian',
        'Indígena.1': 'Native'
}


df_cleaned_Mayor = df_cleaned_Mayor.rename(columns = new_column_names_1)
df_cleaned_City = df_cleaned_City.rename(columns = new_column_names_2)

In [30]:
df_cleaned_Mayor

4,White,Black,Mixed,East Asian,Native,Region,State,Position
17,157,16,263,3,4,Norte,Norte,Mayor
18,29,0,23,0,0,Norte,Rondônia,Mayor
19,4,1,16,0,1,Norte,Acre,Mayor
20,13,0,47,0,1,Norte,Amazonas,Mayor
21,4,1,8,0,2,Norte,Roraima,Mayor
22,41,5,94,1,0,Norte,Pará,Mayor
23,6,1,8,0,0,Norte,Amapá,Mayor
24,60,8,67,2,0,Norte,Tocantins,Mayor
25,812,59,887,8,2,Nordeste,Nordeste,Mayor
26,92,9,115,0,0,Nordeste,Maranhão,Mayor
27,88,7,123,2,0,Nordeste,Piauí,Mayor
28,89,0,88,1,0,Nordeste,Ceará,Mayor
29,109,3,53,1,0,Nordeste,Rio Grande do Norte,Mayor
30,112,5,102,1,1,Nordeste,Paraíba,Mayor
31,100,9,70,0,0,Nordeste,Pernambuco,Mayor
32,52,1,46,1,1,Nordeste,Alagoas,Mayor
33,26,1,46,0,0,Nordeste,Sergipe,Mayor
34,144,24,244,2,0,Nordeste,Bahia,Mayor
35,1302,28,294,4,1,Sudeste,Sudeste,Mayor
36,586,21,231,3,1,Sudeste,Minas Gerais,Mayor
37,57,0,19,1,0,Sudeste,Espírito Santo,Mayor
38,76,1,11,0,0,Sudeste,Rio de Janeiro,Mayor
39,583,6,33,0,0,Sudeste,São Paulo,Mayor
40,1135,1,45,2,1,Sul,Sul,Mayor
41,365,1,29,1,0,Sul,Paraná,Mayor
42,285,0,8,1,0,Sul,Santa Catarina,Mayor
43,485,0,8,0,1,Sul,Rio Grande do Sul,Mayor
44,285,7,161,6,0,Centro-Oeste,Centro-Oeste,Mayor
45,62,1,10,2,0,Centro-Oeste,Mato Grosso do Sul,Mayor
46,90,1,47,1,0,Centro-Oeste,Mato Grosso,Mayor
47,133,5,104,3,0,Centro-Oeste,Goiás,Mayor
48,..,..,..,..,..,Centro-Oeste,Distrito Federal,Mayor

In [31]:
df_cleaned_City

4,White,Black,Mixed,East Asian,Native,Region,State,Position
17,1088,386,3257,25,70,Norte,Norte,City ​​Councilor
18,205,47,269,5,4,Norte,Rondônia,City ​​Councilor
19,37,14,169,4,7,Norte,Acre,City ​​Councilor
20,137,24,522,1,35,Norte,Amazonas,City ​​Councilor
21,21,5,121,0,10,Norte,Roraima,City ​​Councilor
22,387,143,1200,6,7,Norte,Pará,City ​​Councilor
23,31,17,122,0,2,Norte,Amapá,City ​​Councilor
24,270,136,854,9,5,Norte,Tocantins,City ​​Councilor
25,6221,1470,11205,100,55,Nordeste,Nordeste,City ​​Councilor
26,669,194,1507,12,8,Nordeste,Maranhão,City ​​Councilor
27,581,147,1367,16,1,Nordeste,Piauí,City ​​Councilor
28,822,74,1269,6,3,Nordeste,Ceará,City ​​Councilor
29,823,72,742,7,0,Nordeste,Rio Grande do Norte,City ​​Councilor
30,860,104,1183,15,16,Nordeste,Paraíba,City ​​Councilor
31,867,138,1113,4,13,Nordeste,Pernambuco,City ​​Councilor
32,421,34,614,4,4,Nordeste,Alagoas,City ​​Councilor
33,160,76,550,5,1,Nordeste,Sergipe,City ​​Councilor
34,1018,631,2860,31,9,Nordeste,Bahia,City ​​Councilor
35,11289,1144,4781,65,12,Sudeste,Sudeste,City ​​Councilor
36,4623,635,3084,32,7,Sudeste,Minas Gerais,City ​​Councilor
37,479,66,288,3,1,Sudeste,Espírito Santo,City ​​Councilor
38,781,77,288,3,0,Sudeste,Rio de Janeiro,City ​​Councilor
39,5406,366,1121,27,4,Sudeste,São Paulo,City ​​Councilor
40,10360,288,932,13,22,Sul,Sul,City ​​Councilor
41,3101,140,596,9,4,Sul,Paraná,City ​​Councilor
42,2685,41,150,2,4,Sul,Santa Catarina,City ​​Councilor
43,4574,107,186,2,14,Sul,Rio Grande do Sul,City ​​Councilor
44,2151,303,2218,29,25,Centro-Oeste,Centro-Oeste,City ​​Councilor
45,499,47,268,5,13,Centro-Oeste,Mato Grosso do Sul,City ​​Councilor
46,578,104,696,9,11,Centro-Oeste,Mato Grosso,City ​​Councilor
47,1074,152,1254,15,1,Centro-Oeste,Goiás,City ​​Councilor
48,..,..,..,..,..,Centro-Oeste,Distrito Federal,City ​​Councilor

In [32]:
# Melting these two Data Frame to transform columns into rows in a new column 'Race', and keeping the region, state and position column
df_cleaned_Mayor = df_cleaned_Mayor.melt(id_vars = ['Region', 'State', 'Position'], 
                             value_vars = ['White', 'Black', 'Mixed', 'East Asian', 'Native'],
                             var_name = 'Race', 
                             value_name = 'Quantity')


df_cleaned_City = df_cleaned_City.melt(id_vars = ['Region', 'State', 'Position'], 
                             value_vars = ['White', 'Black', 'Mixed', 'East Asian', 'Native'],
                             var_name = 'Race', 
                             value_name = 'Quantity')

In [33]:
# Concating them for the final results
df_Politics = pd.concat([df_cleaned_Mayor, df_cleaned_City])
df_Politics['Year'] = '2020'
df_Politics

           Region               State          Position    Race Quantity  Year
0           Norte               Norte             Mayor   White      157  2020
1           Norte            Rondônia             Mayor   White       29  2020
2           Norte                Acre             Mayor   White        4  2020
3           Norte            Amazonas             Mayor   White       13  2020
4           Norte             Roraima             Mayor   White        4  2020
..            ...                 ...               ...     ...      ...   ...
155  Centro-Oeste        Centro-Oeste  City ​​Councilor  Native       25  2020
156  Centro-Oeste  Mato Grosso do Sul  City ​​Councilor  Native       13  2020
157  Centro-Oeste         Mato Grosso  City ​​Councilor  Native       11  2020
158  Centro-Oeste               Goiás  City ​​Councilor  Native        1  2020
159  Centro-Oeste    Distrito Federal  City ​​Councilor  Native       ..  2020

[320 rows x 6 columns]

In [41]:
# Is going to be the same cleaning process, however there is multiple years to automate
# The code above was to test and check if the Data Frame was clean and ready to use

def process_data(file_path, sheet_name, year):
    # Load the DataFrame from the specified sheet
    df_Politics = pd.read_excel(file_path, sheet_name=sheet_name)
    df_cleaned = df_Politics.copy()

    # Dropping unnecessary rows
    rows_to_drop = [0, 1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 49, 50, 51, 52]
    df_cleaned = df_cleaned.drop(rows_to_drop)

    # Replacing the rows value name for better organization
    replacement_dict = {
        'Branca': 'Branca.1',
        'Preta': 'Preta.1',
        'Parda': 'Parda.1',
        'Amarela': 'Amarela.1',
        'Indígena': 'Indígena.1'
    }
    columns_to_replace = ['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
    df_cleaned[columns_to_replace] = df_cleaned[columns_to_replace].replace(replacement_dict)

    # Setting the columns name with the values of the first row
    df_cleaned.columns = df_cleaned.iloc[0]
    rows_to_drop = [4, 5]
    df_cleaned = df_cleaned.drop(rows_to_drop)

    # Renaming the first column to 'r' (region)
    df_cleaned.columns.values[0] = 'r'

    # Dropping the NaN columns
    columns_to_drop = [col for col in df_cleaned.columns if pd.isna(col)]
    df_cleaned = df_cleaned.drop(columns=columns_to_drop)

    # Creating a dictionary mapping Brazilian states and regions to their respective regions
    Region = {
        'Norte': 'Norte', 'Rondônia': 'Norte', 'Acre': 'Norte', 'Amazonas': 'Norte', 'Roraima': 'Norte', 'Pará': 'Norte', 'Amapá': 'Norte', 'Tocantins': 'Norte',
        'Nordeste': 'Nordeste', 'Maranhão': 'Nordeste', 'Piauí': 'Nordeste', 'Ceará': 'Nordeste', 'Rio Grande do Norte': 'Nordeste', 'Paraíba': 'Nordeste', 'Pernambuco': 'Nordeste', 'Alagoas': 'Nordeste', 'Sergipe': 'Nordeste', 'Bahia': 'Nordeste',
        'Sudeste': 'Sudeste', 'Minas Gerais': 'Sudeste', 'Espírito Santo': 'Sudeste', 'Rio de Janeiro': 'Sudeste', 'São Paulo': 'Sudeste',
        'Sul': 'Sul', 'Paraná': 'Sul', 'Santa Catarina': 'Sul', 'Rio Grande do Sul': 'Sul',
        'Centro-Oeste': 'Centro-Oeste', 'Mato Grosso do Sul': 'Centro-Oeste', 'Mato Grosso': 'Centro-Oeste', 'Goiás': 'Centro-Oeste', 'Distrito Federal': 'Centro-Oeste'
    }

    # Create new columns 'Region' and 'State'
    df_cleaned['Region'] = df_cleaned['r'].apply(lambda x: Region[x] if x in Region else x)
    df_cleaned['State'] = df_cleaned['r'].apply(lambda x: x if x in Region else '')

    # Drop the original column 'r'
    df_cleaned = df_cleaned.drop(columns='r')

    # Separate into Mayor and City Councilor sections
    columns1 = ['Branca', 'Preta', 'Parda', 'Amarela', 'Indígena', 'Region', 'State']
    columns2 = ['Branca.1', 'Preta.1', 'Parda.1', 'Amarela.1', 'Indígena.1', 'Region', 'State']

    df_cleaned_Mayor = df_cleaned[columns1].copy()
    df_cleaned_City = df_cleaned[columns2].copy()

    df_cleaned_Mayor['Position'] = 'Mayor'
    df_cleaned_City['Position'] = 'City Councilor'

    # Translating to English for better understanding
    new_column_names_1 = {
        'Branca': 'White',
        'Preta': 'Black',
        'Parda': 'Mixed',
        'Amarela': 'East Asian',
        'Indígena': 'Native'
    }

    new_column_names_2 = {
        'Branca.1': 'White',
        'Preta.1': 'Black',
        'Parda.1': 'Mixed',
        'Amarela.1': 'East Asian',
        'Indígena.1': 'Native'
    }

    df_cleaned_Mayor = df_cleaned_Mayor.rename(columns=new_column_names_1)
    df_cleaned_City = df_cleaned_City.rename(columns=new_column_names_2)

    # Melting the DataFrames
    df_cleaned_Mayor = df_cleaned_Mayor.melt(id_vars=['Region', 'State', 'Position'], 
                                             value_vars=['White', 'Black', 'Mixed', 'East Asian', 'Native'],
                                             var_name='Race', 
                                             value_name='Quantity')

    df_cleaned_City = df_cleaned_City.melt(id_vars=['Region', 'State', 'Position'], 
                                           value_vars=['White', 'Black', 'Mixed', 'East Asian', 'Native'],
                                           var_name='Race', 
                                           value_name='Quantity')

    # Concatenating the results
    df_Politics = pd.concat([df_cleaned_Mayor, df_cleaned_City])
    df_Politics['Year'] = year

    return df_Politics

# Define file path and years
file_path = 'C:\\Users\\Emerson Wu Li\\Desktop\\Files Para Social... Project\\Tabela 6.1 (Pref_Veread_Eleit_Geo).xls'
years = [2016, 2020]

# Process data for each year and concatenate results
df_Politics = pd.concat([process_data(file_path, str(year), year) for year in years])
df_Politics

           Region               State        Position    Race Quantity  Year
0           Norte               Norte           Mayor   White     3876  2016
1           Norte            Rondônia           Mayor   White      184  2016
2           Norte                Acre           Mayor   White       30  2016
3           Norte            Amazonas           Mayor   White        5  2016
4           Norte             Roraima           Mayor   White       26  2016
..            ...                 ...             ...     ...      ...   ...
155  Centro-Oeste        Centro-Oeste  City Councilor  Native       25  2020
156  Centro-Oeste  Mato Grosso do Sul  City Councilor  Native       13  2020
157  Centro-Oeste         Mato Grosso  City Councilor  Native       11  2020
158  Centro-Oeste               Goiás  City Councilor  Native        1  2020
159  Centro-Oeste    Distrito Federal  City Councilor  Native       ..  2020

[640 rows x 6 columns]

In [44]:
# In this part I only want the position mayor in 2020

df_Politics_Mayor_Region = df_Politics.copy()

# Filtering the States
rows_to_drop = ['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste']
df_Politics_Mayor_Region = df_Politics_Mayor_Region[df_Politics_Mayor_Region['State'].isin(rows_to_drop)]
df_Politics_Mayor_Region = df_Politics_Mayor_Region.drop(columns = "State")

# Filtering the Position
row_to_drop = ['City Councilor']
df_Politics_Mayor_Region = df_Politics_Mayor_Region[~df_Politics_Mayor_Region['Position'].isin(row_to_drop)]

# Filtering the Year
df_Politics_Mayor_Region = df_Politics_Mayor_Region[df_Politics_Mayor_Region['Year'] == 2020]
df_Politics_Mayor_Region

           Region Position        Race Quantity  Year
0           Norte    Mayor       White      157  2020
8        Nordeste    Mayor       White      812  2020
18        Sudeste    Mayor       White     1302  2020
23            Sul    Mayor       White     1135  2020
27   Centro-Oeste    Mayor       White      285  2020
32          Norte    Mayor       Black       16  2020
40       Nordeste    Mayor       Black       59  2020
50        Sudeste    Mayor       Black       28  2020
55            Sul    Mayor       Black        1  2020
59   Centro-Oeste    Mayor       Black        7  2020
64          Norte    Mayor       Mixed      263  2020
72       Nordeste    Mayor       Mixed      887  2020
82        Sudeste    Mayor       Mixed      294  2020
87            Sul    Mayor       Mixed       45  2020
91   Centro-Oeste    Mayor       Mixed      161  2020
96          Norte    Mayor  East Asian        3  2020
104      Nordeste    Mayor  East Asian        8  2020
114       Sudeste    Mayor  East Asian        4  2020
119           Sul    Mayor  East Asian        2  2020
123  Centro-Oeste    Mayor  East Asian        6  2020
128         Norte    Mayor      Native        4  2020
136      Nordeste    Mayor      Native        2  2020
146       Sudeste    Mayor      Native        1  2020
151           Sul    Mayor      Native        1  2020
155  Centro-Oeste    Mayor      Native        0  2020

In [46]:
# In this part I only want the position City Councilor in 2020

df_Politics_City_Region = df_Politics.copy()

# Filtering the States
rows_to_drop = ['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste']
df_Politics_City_Region = df_Politics_City_Region[df_Politics_City_Region['State'].isin(rows_to_drop)]
df_Politics_City_Region = df_Politics_City_Region.drop(columns = "State")

# Filtering the Position
row_to_keep = ['City Councilor']
df_Politics_City_Region = df_Politics_City_Region[df_Politics_City_Region['Position'].isin(row_to_keep)]

# Filtering the Year
df_Politics_City_Region = df_Politics_City_Region[df_Politics_City_Region['Year'] == 2020]
df_Politics_City_Region

           Region        Position        Race Quantity  Year
0           Norte  City Councilor       White     1088  2020
8        Nordeste  City Councilor       White     6221  2020
18        Sudeste  City Councilor       White    11289  2020
23            Sul  City Councilor       White    10360  2020
27   Centro-Oeste  City Councilor       White     2151  2020
32          Norte  City Councilor       Black      386  2020
40       Nordeste  City Councilor       Black     1470  2020
50        Sudeste  City Councilor       Black     1144  2020
55            Sul  City Councilor       Black      288  2020
59   Centro-Oeste  City Councilor       Black      303  2020
64          Norte  City Councilor       Mixed     3257  2020
72       Nordeste  City Councilor       Mixed    11205  2020
82        Sudeste  City Councilor       Mixed     4781  2020
87            Sul  City Councilor       Mixed      932  2020
91   Centro-Oeste  City Councilor       Mixed     2218  2020
96          Norte  City Councilor  East Asian       25  2020
104      Nordeste  City Councilor  East Asian      100  2020
114       Sudeste  City Councilor  East Asian       65  2020
119           Sul  City Councilor  East Asian       13  2020
123  Centro-Oeste  City Councilor  East Asian       29  2020
128         Norte  City Councilor      Native       70  2020
136      Nordeste  City Councilor      Native       55  2020
146       Sudeste  City Councilor      Native       12  2020
151           Sul  City Councilor      Native       22  2020
155  Centro-Oeste  City Councilor      Native       25  2020